Quick/Quick

README.md
Added Carthage instructions and notes regarding the required **Copy Files** build phase.
For #199
=> Add Carthage instructions

Quick.xcodeproj/project.pbxproj, QuickTests/FunctionalTests/SharedExamples+BeforeEachTests+ObjC.m, QuickTests/FunctionalTests/SharedExamplesTests+ObjC.m
Implements the last tickbox from issue #200.
=> Add SharedExamples+BeforeEachTests+ObjC

README.md
Should be a fix for issue #265
=> Mention Nimble in README

Quick.podspec, Quick.xcodeproj/project.pbxproj
This pull request adds the correct Nimble reference to #253 which fixes #206
=> iOS7 Support

Quick.podspec, Quick.xcodeproj/project.pbxproj
=> iOS7 Support, fixes #206

Documentation/InstallingQuick.md
Explicitly specify that .xcworkspace is required
=> Updated installation docs

README.md, circle.yml
Taken from Nimble. Added submodule updating.
CI lives again!
=> Added circle.yml.

Documentation/InstallingQuick.md
=> Add anchors on install options

Quick/Filter.swift, Rakefile
See individual commit messages for details.
=> Fix `rake test:ios` on swift-2.0 branch

Quick.xcodeproj/project.pbxproj
Stop Xcode from prompting to run the swift upgrade tool.
=> Bump the update checks

Documentation/InstallingQuick.md, README.md
Updated instructions for Cocoapods using multiple testing targets
=> Updated Cocoapods instructions

Documentation/InstallingQuick.md
This should help with people experiencing Issue #340. :)
=> Updated installation docs with instructions for Swift 1.2

Quick.podspec
Required to fix deployment to hardware device.
=> Added 'ENABLE_BITCODE' => 'NO' in podspec.

.travis.yml
#370, but against master this time.
=> Add Travis CI (again) (again)

Quick.xcodeproj/project.pbxproj
Implements https://github.com/Quick/Quick/issues/381
=> Add tvOS support

Quick.xcodeproj/project.pbxproj, Quick.xcodeproj/xcshareddata/xcschemes/Quick-tvOS.xcscheme, Quick/Quick.h
Adds tvOS build target
Currently does not support tvOS with UI Testing Bundles.
=> tvOS Support

Documentation/MoreResources.md
404 :-1:  --> New tutorials page: "Support" :+1:
=> Ressurects dead link

Documentation/InstallingQuick.md
Update version numbers with same version in readme
=> Update version numbers in documentation

Quick.podspec, Sources/Quick/Configuration/QuickConfiguration.swift, Sources/Quick/QuickMain.swift, Sources/Quick/QuickSpec.swift
This addresses #463.
Note that I haven't had a chance to properly verify this yet, so that needs to happen before merging please!
=> Update podspec for the new source paths

Sources/Quick/DSL/World+DSL.swift, Sources/QuickTests/FunctionalTests/ItTests.swift
@modocache 
This is a PR to address the concerns you raised when you merged #448. Thanks as always for the feedback.
=> Return only valid phase strings within currentPhase helper function

Documentation/InstallingQuick.md, README.md
From here https://github.com/Quick/Quick/pull/452#issuecomment-174850979
=> Updating documentation to 0.9.0 to include recent release

Documentation/ConfiguringQuick.md, Documentation/QuickExamplesAndGroups.md, Documentation/QuickInObjectiveC.md, Documentation/SettingUpYourXcodeProject.md, Documentation/SharedExamples.md, Documentation/TestingApps.md, Sources/QuickFocusedTests/FocusedTests+ObjC.m, Sources/QuickTests/FunctionalTests/AfterEachTests+ObjC.m, Sources/QuickTests/FunctionalTests/AfterSuiteTests+ObjC.m, Sources/QuickTests/FunctionalTests/BeforeEachTests+ObjC.m, Sources/QuickTests/FunctionalTests/BeforeSuiteTests+ObjC.m, Sources/QuickTests/FunctionalTests/FailureTests+ObjC.m, Sources/QuickTests/FunctionalTests/FailureUsingXCTAssertTests+ObjC.m, Sources/QuickTests/FunctionalTests/ItTests+ObjC.m, Sources/QuickTests/FunctionalTests/PendingTests+ObjC.m, Sources/QuickTests/FunctionalTests/SharedExamples+BeforeEachTests+ObjC.m, Sources/QuickTests/FunctionalTests/SharedExamplesTests+ObjC.m, Sources/QuickTests/Helpers/QCKSpecRunner.h, Sources/QuickTests/Helpers/QCKSpecRunner.m
Fixes the false error @briancroom describes in https://github.com/Quick/Quick/issues/470.
=> use module imports in tests to appease xcode

Documentation/en-us/ArrangeActAssert.md, Documentation/ja/ArrangeActAssert.md
Hi, i also translated ArrangeActAssert.
please review.
takecian.
=> add japanese translation for ArrangeActAssert

Documentation/ja/BehavioralTesting.md, Documentation/ja/NimbleAssertions.md
Hi, i also translated two docs.
Please review again.
=> Add Ja docs

Documentation/ja/QuickExamplesAndGroups.md
translated QuickExamplesAndGroups.
=> add QuickExamplesAndGroups.md

Documentation/ja/QuickExamplesAndGroups.md, Documentation/ja/SharedExamples.md, Documentation/ja/TestingApps.md
hi, i also translated docs.
please review.
Regards,
takecian.
=> translate ja docs

Documentation/en-us/BehavioralTesting.md, Documentation/ja/BehavioralTesting.md
I added image in https://github.com/Quick/Assets/tree/master/Screenshots .
please review.
=> fix image url, fixes #457

CONTRIBUTING.md, script/release
Similar work to https://github.com/Quick/Nimble/pull/284 . ~~Waiting to hear back about attaching binary releases before removing that from the script, too.~~
=> Release process update

circle.yml, script/travis-install-osx
=> Switch back to xctool release builds

Documentation/en-us/SharedExamples.md, Documentation/ja/MoreResources.md, Documentation/ja/SharedExamples.md
Hey guys! While browsing the docs I've noticed minor bugs(?), so I was happy to fix them and make a PR. 🎉
=> [Documentation] Small fixes.

Documentation/ja/InstallingQuick.md
Adjusted a format to the Markdown syntax by removing an extra whitespace.
=> Adjust a format to the Markdown syntax

Documentation/ja/ArrangeActAssert.md, Documentation/ja/BehavioralTesting.md, Documentation/ja/InstallingQuick.md
Removed English text from Japanese documentation.
=> Remove English text

Documentation/zh-cn/SettingUpYourXcodeProject.md
Chinese version of SettingUpYourXcodeProject.md.
=> [Feature] Add Chinese version documents

Documentation/README.md, Documentation/zh-cn/README.md
=> Add README under Documentation folder

Documentation/zh-cn/BehavioralTesting.md
A Chinese version of [BehavioralTesting.md](https://github.com/Quick/Quick/blob/master/Documentation/en-us/BehavioralTesting.md).
=> [Feature] Add a Chinese version document

Documentation/en-us/TestUsingTestDoubles.md
Better english for this one part. Seemed to miss it in the last PR.
=> Editing the more reading line

Documentation/en-us/Troubleshooting.md
Since there seems to be some common issues that users face, it seemed prudent to add a guide to reduce repetitive issues for contributors.
=> added beginnings of a troubleshooting guide for the documentation

Documentation/zh-cn/InstallingQuick.md
A Chinese version of [Installing Quick.md](https://github.com/Quick/Quick/blob/master/Documentation/en-us/InstallingQuick.md).
=> [Translation] Add a Chinese version document

Documentation/zh-cn/BehavioralTesting.md
This PR is the review of **BehavioralTesting** translation.
=> Review BehavioralTesting.md

Documentation/zh-cn/README.md
Correct some punctuation and add a new link
=> [Translation] Update Chinese readme.md

Documentation/zh-cn/NimbleAssertions.md
=> [Translation] NimbleAssertions.md

Documentation/zh-cn/Troubleshooting.md
=> [Translation] Troubleshooting.md

Documentation/zh-cn/MoreResources.md
=> [Translation] MoreResources.md

Documentation/pt-br/BehavioralTesting.md
Continues #610
@marciok can you review it? 😉
=> [Translation] Translates BehavioralTesting to pt-BR 

README.md
Describe Swift version and that supports Quick and Nimble release version.
=> [Documentation] Add Swift version in README

README.md
=> [README] Fix Swift version descriptions

Documentation/en-us/TestUsingTestDoubles.md
Some miscellaneous code and text updates to the test double/mocks documentation.
Please let me know anything I can do to improve this PR! Happy to rebase some of the changes out if you don't prefer them.
=> Test double doc updates

.travis.yml
=> [.travis.yml] Remove `PLATFORM=linux` env variable to avoid conflict with swiftenv

Documentation/en-us/SettingUpYourXcodeProject.md
Fixed the merge conflict from #456.
Props to @masukomi.
=> Masukomi: Improved documentation for Xcode Project Setup

Documentation/zh-cn/README.md, Documentation/zh-cn/SharedExamples.md
=> [Documentation] Translation for SharedExamples.md

Sources/Quick/World.swift, Tests/LinuxMain.swift, Tests/QuickTests/QuickFocusedTests/FocusedTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/AfterEachTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/BeforeEachTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/BeforeSuiteTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/Configuration/AfterEach/Configuration+AfterEachTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/Configuration/BeforeEach/Configuration+BeforeEachTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/DescribeTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/PendingTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/SharedExamples+BeforeEachTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/SharedExamplesTests.swift
Trivial , but I like my builds clean of warnings.
=> Remove Swiftlint warnings.

Sources/Quick/DSL/DSL.swift, Sources/Quick/DSL/World+DSL.swift, Tests/QuickTests/QuickFocusedTests/FocusedTests.swift
Fix #643
Port fitBehavesLike to Swift
=> Port `fitBehavesLike` to Swift

Sources/Quick/Callsite.swift, Sources/Quick/Example.swift
https://github.com/apple/swift-evolution/blob/master/proposals/0091-improving-operators-in-protocols.md
=> [WIP] Implement `==` operator as a static function

Quick Templates/Quick Configuration Class.xctemplate/Swift/___FILEBASENAME___.swift
This is missed for Swift 3 update.
=> Update QuickConfiguration template

Documentation/en-us/SettingUpYourXcodeProject.md
As per this discussion: https://github.com/Quick/Quick/issues/665
=> Added a comment about Xcode limitations

Sources/Quick/Configuration/Configuration.swift, Sources/Quick/DSL/DSL.swift, Sources/Quick/DSL/World+DSL.swift, Sources/Quick/Example.swift, Sources/Quick/ExampleGroup.swift, Sources/Quick/Hooks/Closures.swift, Sources/Quick/World.swift
=> [SwiftLint] Correct void_return rule

Sources/Quick/DSL/DSL.swift, Tests/QuickTests/QuickTestHelpers/XCTestCaseProvider.swift
=> Use trailing closures where possible

Documentation/pt-br/SharedExamples.md
Another small step on #610 
Special trouble to translate "that's the way the cookie crumbles!" 😄
=> Translates SharedExamples to pt-BR

.Package.test.swift, .travis.yml, Package.swift, Quick.xcodeproj/project.pbxproj, Sources/Quick/Configuration/QuickConfiguration.swift, Sources/Quick/QuickMain.swift, Sources/Quick/QuickSpec.swift, Sources/Quick/World.swift, Sources/QuickSpecBase/QuickSpecBase.m, Sources/QuickSpecBase/include/QuickSpecBase.h, Tests/LinuxMain.swift, Tests/QuickTests/QuickFocusedTests/FocusedTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/BundleModuleNameTests.swift
This is based on the discussions in #679 (and my some experiments). I've confirmed this basically works with the specs of ReactiveSwift locally.
Resolves #679, resolves #600.
=> Add SwiftPM support on macOS

Sources/Quick/NSString+C99ExtendedIdentifier.swift
=> [NSString] Refactor `c99ExtendedIdentifier` a bit

Sources/QuickObjectiveC/QuickSpec.m
That is a very simple operation now.
Just a minor refactoring.
=> [gardening][QuickSpec] Inline `+invocationForInstanceMethodWithSelector:example:`

Sources/Quick/NSString+C99ExtendedIdentifier.swift
=> [SwiftLint][trivial] Resolve trailing comma violation

Tests/QuickTests/QuickTests/FunctionalTests/CrossReferencingSpecs.swift
Removed a couple of warnings in QuickTests.
=> Remove SwiftLint warnings

Sources/Quick/QuickTestSuite.swift
=> [gardening] Utilize the return value of `Set.insert`

Tests/QuickTests/QuickTests/FunctionalTests/AfterEachTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/BeforeEachTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/BehaviorTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/ContextTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/DescribeTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/SharedExamplesTests.swift
=> Revert "[gardening] Remove redundant OS checks"

Documentation/ja/ConfiguringQuick.md
- [-] Does this have tests?
- [-] Does this have documentation?
=> Fix japanese document typo.

.swiftlint.yml, .travis.yml, Quick.xcodeproj/project.pbxproj, Sources/Quick/Callsite.swift, Sources/Quick/DSL/World+DSL.swift, Sources/Quick/Example.swift, Sources/Quick/ExampleMetadata.swift, Sources/Quick/Filter.swift, Sources/Quick/QuickTestSuite.swift, Sources/Quick/World.swift, Tests/QuickTests/QuickFocusedTests/FocusedTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/BehaviorTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/PendingTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/SharedExamplesTests.swift
=> Support both Swift 3.x and Swift 4

Sources/Quick/ExampleGroup.swift
There is no behavioral change.
=> [ExampleGroup] Minor refactoring

Documentation/en-us/ConfiguringQuick.md
=> make Swift snippets for QuickConfiguration compile

.gitignore, Package.resolved
https://github.com/Quick/Nimble/releases/tag/v7.0.3
=> Update Nimble to 7.0.3

Package.resolved
=> [SwiftPM] Update Nimble

Package.resolved
https://github.com/Quick/Nimble/pull/517
=> Update Nimble to 7.1.1

Quick.podspec
=> [podspec] Bump osx.deployment_target to 10.10

Quick.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
https://medium.com/xcblog/xcode-new-build-system-for-speedy-swift-builds-c39ea6596e17
This is non-functional change but will improve build time.
=> [Xcode] Enable New Build System

Package.resolved
https://github.com/Quick/Nimble/releases/tag/v7.1.3
For `master`: #808
=> [1.x] Update Nimble to 7.1.3

Quick.xcodeproj/project.pbxproj
Cherry-picks #817 into `1.x-branch`.
=> [1.x] Xcode 10: Adjust Build Phases order

.travis.yml
=> [CI] Add Swift 4.2/Xcode 10 to the build matrix

Sources/Quick/Behavior.swift
Cherry-picks #821 into 1.x-branch.
=> [1.x] Fix Xcode 10 warning

Package.resolved, Package.swift
https://github.com/Quick/Nimble/releases/tag/v8.0.0
=> Update Nimble to 8.0.0

.hound.yml, .travis.yml, Rakefile, script/travis-install-macos
=> [CI] Add Xcode 10.2 image to the build matrix

Quick.xcodeproj/project.pbxproj, Quick.xcodeproj/xcshareddata/xcschemes/Quick-iOS.xcscheme, Quick.xcodeproj/xcshareddata/xcschemes/Quick-macOS.xcscheme, Quick.xcodeproj/xcshareddata/xcschemes/Quick-tvOS.xcscheme
Let's suppress warnings on Xcode 10.2.
=> Xcode 10.2: Update to recommended settings

Sources/Quick/Callsite.swift, Sources/Quick/DSL/DSL.swift, Sources/Quick/DSL/World+DSL.swift
This is a preliminary task for #680, based on https://github.com/Quick/Nimble/blob/5eccb9524614fdd8bed37e6ea6f6dcbca6c8258e/Sources/Nimble/Utils/SourceLocation.swift#L3-L12.
=> Introduce FileString typealias which has been used in Nimble

Quick.xcodeproj/project.pbxproj, Tests/QuickTests/QuickTests/Helpers/QCKSpecRunner.m
=> Update SWIFT_OBJC_INTERFACE_HEADER_NAME of test targets with fixed values

Quick.xcodeproj/project.pbxproj, Tests/QuickTests/QuickTests/Helpers/QCKSpecRunner.m, Tests/QuickTests/QuickTests/Helpers/QuickSpecRunner.swift, Tests/QuickTests/QuickTests/Helpers/QuickTestsBridgingHeader.h
Similar to #860, #859 (and based on #858).
=> [refactoring] Implement QCKSpecRunner in Swift

Package@swift-4.2.swift
=> [SwiftPM] Update Package@swift-4.2.swift as well

Tests/QuickTests/QuickTestHelpers/SpecRunner.swift, Tests/QuickTests/QuickTests/Helpers/QuickSpecRunner.swift
Just minor refactoring / fixes.
=> Tweak QuickSpecRunner

Tests/QuickTests/QuickTests/Helpers/QuickSpecRunner.swift
=> Refactor QuickSpecRunner a bit

Sources/Quick/Callsite.swift, Sources/Quick/DSL/World+DSL.swift, Sources/Quick/Example.swift, Sources/Quick/ExampleMetadata.swift, Sources/Quick/Filter.swift, Sources/Quick/World.swift
=> Remove unnecessary `!SWIFT_PACKAGE` compile condition

Quick.podspec, Quick.xcodeproj/project.pbxproj, Sources/Quick/Configuration/QuickConfiguration.swift, Sources/Quick/QuickSpec.swift, Sources/QuickObjectiveC/Configuration/QuickConfiguration.m
=> [refactoring] Re-implement qck_enumerateSubclasses in Swift

.travis.yml
=> ⚠️ Re-enable danger 🙀

Sources/Quick/Configuration/QuickConfiguration.swift, Sources/Quick/QuickSpec.swift, Sources/QuickObjectiveC/Configuration/QuickConfiguration.m
This does not affect SwiftPM-Linux integration.
=> Refactor configuring QuickConfiguration subclasses

Sources/Quick/World.swift, Tests/QuickTests/QuickTests/Helpers/QuickSpecRunner.swift
This is a step to correctly test #680 in SwiftPM. And also this is a bit related to #435 I think.
=> Run additional test suites in a separate World instance (only with Xcode for now)

Sources/Quick/QuickSpec.swift, Sources/QuickObjectiveC/QuickSpec.m, Tests/QuickTests/QuickTests/Helpers/QuickSpecRunner.swift
=> Run additional test suites in a separate World instance for SwiftPM on Darwin

Tests/QuickTests/QuickTests/Helpers/QuickSpecRunner.swift, Tests/QuickTests/QuickTests/Helpers/XCTestObservationCenter+QCKSuspendObservation.swift
Refs:
- #680 
- #859 
- #861 
- #879 
- #882 
https://github.com/Quick/Quick/pull/883/files?w=1
=> Implement `qck_suspendObservation` on Linux

Sources/Quick/Configuration/QuickConfiguration.swift, Sources/Quick/QuickMain.swift, Sources/Quick/QuickSpec.swift, Tests/QuickTests/QuickTests/Helpers/QuickSpecRunner.swift
=> Run additional test suites in a separate World instance for SwiftPM on Linux

Tests/QuickTests/QuickTests/Helpers/QuickSpecRunner.swift
Refs:
- #680 
- #883 
- #884 
---
Unify the implementation with Darwin as much as possible. https://github.com/apple/swift-corelibs-xctest/blob/51afda0bc782b2d6a2f00fbdca58943faf6ccecd/Sources/XCTest/Private/XCTestCaseSuite.swift#L14-L42 did help us.
=> Re-implement SpecRunner on Linux using XCTestSuite

.travis.yml
=> [CI] Test Swift 5.1 snapshots

Sources/Quick/World.swift
Added in 0.32.0: https://github.com/realm/SwiftLint/releases/tag/0.32.0.
For readability and performance improvement.
=> [SwiftLint] Address reduce_boolean warnings

Quick.xcodeproj/project.pbxproj
- https://github.com/Quick/Nimble/releases/tag/v8.0.2
- https://github.com/Quick/Nimble/pull/670
=> Update Nimble to 8.0.2

Documentation/en-us/SharedExamples.md, Documentation/ja/SharedExamples.md, Documentation/ko-kr/SharedExamples.md, Documentation/pt-br/SharedExamples.md, Documentation/zh-cn/SharedExamples.md
Missing Caret - ^ in Objective-C code
=> fix typo in SharedExamples.md

.github/workflows/ci.yml, .travis.yml, Gemfile, Gemfile.lock, Rakefile
Refs:
- https://github.com/Quick/Nimble/pull/676 
- https://github.com/Quick/Nimble/pull/679
=> [CI] Use GitHub Actions for macOS jobs

.travis.yml, Quick.podspec
Closes #895. Supersedes #911.
/cc @ethansinjin
=> [podspec] Use swift_versions DSL if available

.github/workflows/ci.yml
=> [CI] Add pull_request event to run tests for pull requests from forked repositories

.github/ISSUE_TEMPLATE
=> Fix typo in GitHub issue template

CONTRIBUTING.md
=> Fix typos in Contributing documentation file

Documentation/ja/SharedExamples.md
Updated to work with swift 4.0 and later.
=> Migration swift 4.0 or later for Shared Examples.

.github/workflows/ci.yml, .travis.yml
- GitHub Actions
- Xcode 11.3
- Travis (for Linux)
- Swift 5.1
- Swift 5.2 Development
=> [CI] Run tests with newer Xcode and Swift versions

Documentation/ko-kr/SharedExamples.md, Documentation/pt-br/SharedExamples.md, Documentation/zh-cn/SharedExamples.md
=> Fix sample code in SharedExamples.md

Package.resolved
- https://github.com/Quick/Nimble/releases/tag/v8.0.7
- https://github.com/Quick/Nimble/releases/tag/v8.0.6
- https://github.com/Quick/Nimble/releases/tag/v8.0.5
=> Update Nimble to 8.0.7

.github/workflows/swiftlint.yml, .hound.yml, Dangerfile, Gemfile, Gemfile.lock, README.md
=> [CI] Use norio-nomura/action-swiftlint for running SwiftLint

.github/workflows/ci.yml
- https://github.com/Quick/Nimble/releases/tag/v8.0.9
- https://github.com/Quick/Nimble/releases/tag/v8.0.8
=> Update Nimble to 8.0.9

.swiftlint.yml, Sources/Quick/Callsite.swift, Sources/Quick/Example.swift, Sources/Quick/ExampleMetadata.swift, Sources/Quick/Filter.swift, Sources/Quick/World.swift, Tests/.swiftlint.yml
=> [SwiftLint] Enable type_name rule

.swiftlint.yml, Sources/Quick/Configuration/QuickConfiguration.swift, Sources/Quick/QuickSpec.swift, Tests/.swiftlint.yml
=> [SwiftLint] Enable identifier_name rule

.swiftlint.yml, Sources/Quick/Behavior.swift, Sources/Quick/DSL/DSL.swift, Sources/Quick/DSL/World+DSL.swift, Sources/Quick/World.swift, Tests/.swiftlint.yml, Tests/QuickTests/QuickTests/FunctionalTests/AfterEachTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/BeforeEachTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/BehaviorTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/ContextTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/DescribeTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/SharedExamplesTests.swift
=> [SwiftLint] Enable line_length rule

Quick.xcodeproj/project.pbxproj
Removes duplicate target dependencies.
=> Fix test target dependencies

.swiftlint.yml, Sources/Quick/Configuration/Configuration.swift, Sources/Quick/String+C99ExtendedIdentifier.swift, Tests/LinuxMain.swift, Tests/QuickTests/QuickFocusedTests/FocusedTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/AfterEachTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/BeforeEachTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/BeforeSuiteTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/BehaviorTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/Configuration/AfterEach/Configuration+AfterEachTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/Configuration/BeforeEach/Configuration+BeforeEachTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/DescribeTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/PendingTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/SharedExamples+BeforeEachTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/SharedExamplesTests.swift
=> [SwiftLint] Set trailing_comma's mandatory_comma option to true

Package.resolved
=> Update Nimble for SwiftPM

.github/workflows/ci.yml
=> Parallelize CI builds more (Take 2)

Package.resolved, Package.swift
https://github.com/Quick/Nimble/releases/tag/v9.0.0-rc.1
=> Update Nimble to 9.0.0-rc.1

.github/workflows/ci.yml, .travis.yml, Sources/Quick/QuickSpec.swift
=> Update CI config for 2.x-branch

Quick.xcodeproj/project.pbxproj
=> Upgrade Project Format to Xcode 11.4-compatible

Package.swift, Quick.podspec, Quick.xcodeproj/project.pbxproj
Mainly for Xcode 12 compatibility.
ref: https://github.com/Quick/Nimble/pull/825
=> [BREAKING] Bump minimum iOS version to 9.0

Quick.xcodeproj/project.pbxproj
refs:
- #158 
- https://github.com/Quick/Nimble/pull/827
Supersedes #1003.
Thank you @mRs- for the original pull request!
=> Support ARM based Macs (Apple Silicon)

Package.resolved, Package.swift, Tests/QuickTests/QuickTests/FunctionalTests/AfterEachTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/BeforeEachTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/BehaviorTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/ContextTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/DescribeTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift, Tests/QuickTests/QuickTests/FunctionalTests/SharedExamplesTests.swift
https://github.com/Quick/Nimble/releases/tag/v9.0.0
=> Update Nimble to 9.0.0

Package.resolved, Package.swift, Package@swift-5.3.swift, Rakefile
=> [3.x] Add Package@swift-5.3.swift to bump minimum iOS version for SwiftPM users

Quick.xcodeproj/project.pbxproj
Cherry-picks #1017 into `3.x-branch`.
=> [3.x] Support ARM based Macs (Apple Silicon)

Sources/Quick/Example.swift, Sources/QuickObjectiveC/QuickSpec.m
https://developer.apple.com/documentation/xctest/xctestcase/3546549-record#
ref: https://github.com/Quick/Nimble/pull/830
=> Address deprecation warnings in Xcode 12

.github/workflows/ci.yml
https://hub.docker.com/r/norionomura/swift/
=> [CI] Use norionomura/swift Docker images for Linux CI

.swiftlint.yml
https://realm.github.io/SwiftLint/yoda_condition.html
ref: https://github.com/Quick/Nimble/pull/847#discussion_r571092554
=> [SwiftLint] Enable yoda_condition rule

Sources/QuickObjCRuntime/include/QuickObjCRuntime.h
ref: #984
Should fix #997 and supersedes #1006.
=> Add the umbrella header for QuickObjCRuntime target

Sources/QuickObjCRuntime/include/QuickObjCRuntime.h
Cherry-picks #1023 into `3.x-branch`.
=> [3.x] Add the umbrella header for QuickObjCRuntime target

.github/workflows/ci.yml
=> [CI] Use the official Swift Docker images

.github/workflows/ci-swiftpm.yml, .github/workflows/ci-xcode.yml, .github/workflows/cocoapods.yml, .github/workflows/danger.yml
Would reduce CI time consumption.
=> [CI] Split ci.yml into dedicated workflows

.github/workflows/ci-swiftpm.yml, .github/workflows/ci-xcode.yml, .github/workflows/cocoapods.yml
refs:
- #1050 
- https://github.com/fkirc/skip-duplicate-actions/issues/56
=> Tweak CI workflows regarding fkirc/skip-duplicate-actions and matrix testing

.github/ISSUE_TEMPLATE, .github/workflows/ci-swiftpm.yml, .github/workflows/ci-xcode.yml, .github/workflows/cocoapods.yml, CONTRIBUTING.md, Documentation/en-us/InstallingQuick.md, Documentation/ja/InstallingQuick.md, Documentation/ko-kr/InstallingQuick.md, Documentation/zh-cn/InstallingQuick.md, README.md, script/release
=> Rename master branch to main

Quick.xcodeproj/project.pbxproj, Quick.xcodeproj/xcshareddata/xcschemes/Quick-iOS.xcscheme, Quick.xcodeproj/xcshareddata/xcschemes/Quick-macOS.xcscheme, Quick.xcodeproj/xcshareddata/xcschemes/Quick-tvOS.xcscheme
=> Xcode 12.5: Update to recommended settings

.github/workflows/ci-swiftpm.yml, .github/workflows/ci-xcode.yml
https://swift.org/blog/swift-5-4-released/
=> [CI] Update Xcode and Swift versions

Package.resolved, Package.swift
https://github.com/Quick/Nimble/releases/tag/v9.1.0
=> Update Nimble to 9.1.0

Sources/Quick/DSL/DSL.swift, Sources/Quick/DSL/World+DSL.swift, Sources/Quick/Filter.swift, Sources/QuickObjectiveC/DSL/QCKDSL.h, Sources/QuickObjectiveC/DSL/QCKDSL.m
To prevent confusion like #800.
=> [BREAKING] Make FilterFlags implementation detail

Documentation/en-us/DataDrivenExamples.md, Documentation/en-us/README.md
No behaviour was changed, this PR only adds documentation.
Fixes #890
=> Added documentation for how to do data driven tests using Quick

Documentation/en-us/DataDrivenExamples.md
- What issues are related to this PR? Or why was this change introduced? #940
=> Fix typos and code issues in the data driven examples documentation

Documentation/en-us/InstallingQuick.md, README.md
=> [README] Remove deprecated Accio references

Sources/Quick/Example.swift
ref: https://github.com/Quick/Quick/pull/1040#pullrequestreview-738650721
=> Use `#if canImport(Darwin)` for checking XCTIssue availability

Sources/Quick/Configuration/QuickConfiguration.swift, Sources/Quick/QuickTestObservation.swift
=> Keep reference to AutoreleasingUnsafeMutablePointer

Quick.xcodeproj/project.pbxproj, Sources/Quick/Configuration/QCKConfiguration.swift, Sources/Quick/Configuration/QuickConfiguration.swift, Sources/Quick/World.swift, Sources/QuickObjectiveC/Configuration/QuickConfiguration.h, Sources/QuickObjectiveC/Configuration/QuickConfiguration.m, Tests/QuickTests/QuickFocusedTests/FocusedTests+ObjC.m, Tests/QuickTests/QuickFocusedTests/FocusedTests.swift, Tests/QuickTests/QuickTests/Fixtures/FunctionalTests_SharedExamplesTests_SharedExamples.swift, Tests/QuickTests/QuickTests/FunctionalTests/Configuration/AfterEach/Configuration+AfterEach.swift, Tests/QuickTests/QuickTests/FunctionalTests/Configuration/BeforeEach/Configuration+BeforeEach.swift, Tests/QuickTests/QuickTests/FunctionalTests/ObjC/SharedExamples+BeforeEachTests+ObjC.m, Tests/QuickTests/QuickTests/FunctionalTests/SharedExamples+BeforeEachTests.swift
=> [Breaking] Rename Configuration -> QCKConfiguration

Documentation/en-us/ConfiguringQuick.md, Documentation/ja/ConfiguringQuick.md, Documentation/ko-kr/ConfiguringQuick.md, Documentation/zh-cn/ConfiguringQuick.md
#1133 renamed Configuration to QCKConfiguration.
This PR follows the change on documentation.
=> Renamed Configuration -> QCKConfiguration on documentation

.github/funding.yml
Following up from https://github.com/Quick/Quick/pull/1147.
I finally got around to setting up GitHub sponsors, so adding myself to the people to sponsor for Quick and Nimble.
=> Add @younata to funding.yml

.github/workflows/ci-swiftpm.yml, .github/workflows/ci-xcode.yml
Xcode 14 has been out for a month now, we should check against it in CI.
=> Add support for xcode 14 and swift 5.7

Documentation/ko-kr/AsyncAwait.md
Added Korean translation of AsyncAwait documentation.
=> [Translation] AsyncAwait.md Korean translation

Package.resolved, Package.swift
Bumps Nimble to the new v12 version.
=> Update Nimble to v12

Package.swift, Quick.xcodeproj/project.pbxproj, README.md, Sources/Quick/PrivacyInfo.xcprivacy
=> Add a privacy manifest

script/release
Prevent https://github.com/Quick/Quick/issues/1262 in the general case.
=> Release script should auto-update local ruby dependencies

Documentation/ko-kr/SettingUpYourXcodeProject.md
There was a typo in the Korean word meaning navigation, so it was corrected.
=> Corrected typo in document

.github/workflows/carthage.yml, .github/workflows/cocoapods.yml, .github/workflows/danger.yml
=> Bump ruby version in github workflows
