README.md

Punctuation is ignored by GitHub in the h2 links.
Simple fix... love the project :)

Fix #start-writing-specs Link in README

---

README.md

This pull request is in regards to #163.  It provides README documentation for Quick Configuration.  Let me know if you need anything changed, added, or removed.  Glad to contribute :)

Add Configuration Information to README

---

README.md

Finally trying out Quick (& Carthage at the same time), great test library (was using Kiwi before).
In the README.md, the carthage installation seems to be missing the Nimble line (used afterwards).
Thanks!

Carthage install: Add Nimble to cartfile.private

---

Quick/DSL/QCKDSL.h

Somehow this managed to sneak in there without anyone noticing :wolf:

Fix typo in Objective-C DSL

---

Quick.xcodeproj/project.pbxproj

I've found that xcodebuild will often select the wrong version of xctest.framework and as such fail to compile Quick.framework.
This pull request removes the inclusion of xctest.framework from Quick-iOS and Quick-OSX. It also simplifies the framework search path to only include $(inherited) $(PLATFORM_DIR)/Developer/Library/Frameworks.

Simplify framework search paths to avoid finding the wrong xctest.framework

---

Quick.podspec
README.md

I'd like to add Quick to [CocoaPods Trunk](http://guides.cocoapods.org/making/getting-setup-with-trunk.html) so that others may use it more easily and may also write pods using [quick as a dependency](https://github.com/ashfurrow/Nimble-Snapshots/issues/19). This pull requests contains updates to the README, as well as an update to bump the podspec to [0.2.2](https://github.com/Quick/Quick/releases/tag/v0.2.2)
Once this is merged, someone will need to push this to CocoaPods Trunk. I'm happy to do it, happy to add others as owners, and happy to allow someone else to do it altogether. Just let me know, @Quick/owners .

Add to Cocoapods Trunk

---

README.md

We might support Xcode versions greater than 6 beta 4 :wink:.
Also worth asking: are the version numbers enough to indicate beta-ness of Quick? If not, I can leave that part of the notice there.

Removed beta xcode warning in README.

---

CONTRIBUTING.md
Quick/DSL/DSL.swift
Quick/DSL/QCKDSL.m
Quick/DSL/World+DSL.swift
QuickTests/Fixtures/FunctionalTests_SharedExamplesTests_SharedExamples.swift
QuickTests/FunctionalTests/AfterSuiteTests.swift
QuickTests/FunctionalTests/BeforeSuiteTests.swift
README.md

Builds upon @mprudhom's changes in #244. These changes get the tests passing using Xcode 6.3 and Swift 1.2. Of course, since Travis CI doesn't support Swift 1.2, CI does not pass on this branch.

Support Swift 1.2

---

README.md

I noticed that the readme was missing a link to "How to Install Quick using Carthage" section from the table of contents, so I added it. Sublime Text also trimmed some unnecessary whitespace from it :convenience_store:

Add "How to Install Quick using Carthage" to table of contents

---

Documentation/ArrangeActAssert.md

The tests for offering to peal the banana were testing the wrong cases (testing the peeled message when the banana wasn't peeled and vice versa).

Updates tests in ArrangeActAssert to be correct

---

README.md

It took me a while to find out that the documentation was moved to a separate directory. (I remember when it was in the README.) I think this will help with any confusion in the future for others.

Add link to new documentation in README

---

Documentation/InstallingQuick.md

Cocoapods Version 0.36.0 with Swift Support has been released, so the install-instructions for Cocoapods had to be updated.

Updated InstallingQuick Documentation for Cocoapods 0.36.0

---

Quick.podspec

Worth noting is on v0.2.2 (what the current podspec is pointing to), in DSL.swift, the func `it` reads:
```public func it(description: String, closure: () -> (), flags: FilterFlags = [:], file: String = __FILE__, line: Int = __LINE__) ```
Which will not allow the syntax in the readme
```it("has everything you need to get started") { }```
to work, as the closure is not yet updated to be at the end of the func declaration. I would expect this to be causing problems with users who are using the cocoapods beta.

Bumped Podspec version to 0.3.0

---

Documentation/QuickExamplesAndGroups.md

exmaples —> examples in `QuickExamplesAndGroups.md`

A small typo in documentation

---

Quick.podspec
Quick.xcodeproj/project.pbxproj

Depends on https://github.com/Quick/Nimble/pull/118. Once that's merged, this pull request should be update Externals/Nimble to point at v0.4.2.
Quick and Nimble can be used to test code running against on iOS 7.0, but their deployment targets were set too high in order to do so. Lower Quick's deployment target to make this possible.
Unfortunately, a warning is generated during the linking phase for Quick-iOS: "ld: warning: embedded dylibs/frameworks only run on iOS 8 or later". I'm not sure if this is avoidable. I'm no expert, though, I just skimmed ReactiveCocoa/ReactiveCocoa#1480.
A new release should be made after merging these changes.
Addresses #276.

Quick.xcodeproj: Lower iOS deployment target to 7.0

---

CONTRIBUTING.md

Hey there!
These are 2 really small things I ran into when working on something else.
- The first is that the command for running ios and osx tests is just `rake` rather than `rake test`. If you prefer, I can change the Rakefile so that it'll be `rake test` instead of changing the docs.
- The second is just a comment about updating the submodule just so other people forking and cloning for the first time will know what to do if they run into that issue.
Thank you very much! :rocket:

Contributing guide clarifications

---

Documentation/InstallingQuick.md

This will make the link to Carthage.private look like this [`Carthage.private`](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#cartfileprivate). Most likely a typo while writing the documentation.
Documentation which is great btw, very informative and thorough. I especially like how it first focuses on teaching the bases of good tests, then _sells_ Quick. Very well done. Thanks!

Markdown syntax fix in link to Carthage.private docs

---

circle.yml

I was wrong about the circleci setup stuff.
Being more implicit for xcodebuild seems to make it build the dependent Nimble.framework for Quick-OSX.
Since it would be nearly the same as running the rake tasks, I've converted them to the rake tasks.
Hopefully, this should resolve all the inconsistent CI failures we've been experiencing.

[CI] Use rakefile task instead of xcodebuild directly

---

.gitignore
Quick.xcodeproj/project.pbxproj
Quick.xcodeproj/xcshareddata/xcschemes/Quick-OSX.xcscheme
Quick.xcodeproj/xcshareddata/xcschemes/Quick-iOS.xcscheme
Quick/DSL/DSL.swift
Quick/DSL/World+DSL.swift
Quick/ExampleGroup.swift
Quick/Info.plist
Quick/World.swift
QuickFocusedTests/Info.plist
QuickTests/FunctionalTests/AfterSuiteTests.swift
QuickTests/FunctionalTests/BeforeSuiteTests.swift
QuickTests/Helpers/QCKSpecRunner.m
QuickTests/Helpers/XCTestObservationCenter+QCKSuspendObservation.h
QuickTests/Info.plist
README.md
circle.yml

1. Update .gitmodules to pull in Nimble Swift 2.0 support
(https://github.com/Quick/Nimble/pull/131).
2. Run Edit > Convert > To Latest Swift Syntax.
3. XCTestObservationCenter is now a public XCTest API, although it
doesn't expose "suspend observation". Expose that method via a category.
---
This pull request supersedes #312, and targets the `swift-2.0` branch.

Support Swift 2.0 on separate branch

---

Documentation/QuickExamplesAndGroups.md
Quick/DSL/DSL.swift
Quick/DSL/QCKDSL.h
Quick/DSL/QCKDSL.m
Quick/DSL/World+DSL.swift
QuickTests/FunctionalTests/ItTests+ObjC.m
QuickTests/FunctionalTests/ItTests.swift

A goal for Quick v1.0 is to no longer expose the `Quick.World` singleton. This is made harder by the fact that our very own tests use it!
Bridge `beforeEach` and `afterEach` closures that take example metadata arguments to Objective-C, in order to allow `ItTests+ObjC.m` to not use "private" APIs.

Bridge example metadata to Objective-C

---

Quick.xcodeproj/project.pbxproj
Quick/Configuration/QuickConfiguration.m
Quick/DSL/QCKDSL.m
Quick/DSL/World+DSL.h
Quick/DSL/World+DSL.swift
Quick/QuickSpec.m
Quick/World.h
Quick/World.swift
QuickTests/Helpers/QCKSpecRunner.m

This must be merged **after** #302. This pull request is a revision of #287.
---
One of Quick's greatest design flaws is due to the combination
of four factors:
1. Quick has a predilection for Swift--one of it's goals was to be
written entirely in Swift if possible.
2. Quick supports tests written in both Swift and Objective-C.
3. XCTest relies upon subclassing for test discovery.
4. Objective-C classes cannot subclass Swift base classes.
As such, Quick is unable to define QuickSpec, a base XCTestCase
subclass, in Swift, and then have both Objective-C and Swift tests
subclass QuickSpec.
Instead, in order to be used from both Swift and Objective-C, QuickSpec
must be implemented in Objective-C. This forces internal Quick code,
such as Quick.World, to be marked as public. People using Quick …

Forward-declare World, which is now internal

---

Quick.xcodeproj/project.pbxproj
Quick/QuickSpec.m
QuickTests/FunctionalTests/FailureTests+ObjC.m
QuickTests/FunctionalTests/FailureUsingXCTAssertTests+ObjC.m

Fixes #121. See individual commit messages for details.
---
I wanted to make sure `XCTAssert` macros also worked within shared examples, but that brought up a separate issue: since shared examples are now typically defined within `+[QuickConfiguration configure:]`, a class method, `XCTAssert` macros raise a warning:
> Incompatible pointer types passing 'Class' to parameter of type 'XCTestCase'
We may have to change the configuration API in order to support `XCTAssert` macros in shared examples... I'll file a separate issue for this, unless any reviewers think it's not an issue that should be considered separately from this PR.

Support XCTestAssert macros in Quick specs written in Objective-C

---

Quick.podspec

Talked to @modocache and the change to make this 10.10 was unintentional.

[Podspec] Restore support for OS X 10.7

---

Quick/Configuration/Configuration.swift
Quick/DSL/DSL.swift
Quick/DSL/World+DSL.swift
Quick/World.swift

Ran through Xcode 7 beta 2's Swift Syntax Migrator.
Fixes support for carthage too. Fixes #325.

Xcode7b2 migration

---

Quick.xcodeproj/project.pbxproj

XCTest framework doesn't have bitcode enabled, since Xcode beta 3 it's treated as an error, there is probably a better solution out there :-)

Swift and Xcode 7 beta 3 compatibility fix

---

Documentation/ArrangeActAssert.md

in [Effective Tests Using XCTest: Arrange, Act, and Assert](https://github.com/Quick/Quick/blob/swift-2.0/Documentation/ArrangeActAssert.md)
you should use ```public var isEdible``` instead of ```private var isPeeled``` in Banana/Offer.swift.

Fix access value in document

---

Documentation/InstallingQuick.md
README.md

CocoaPods link_with does not do what I thought it does! Updated the README and Installation Instructions with the correct way (thanks [@neonichu](https://gist.github.com/neonichu/16ce4cca9f0b8230f8ba)) of linking the testing pods against both the Unit Test and the new UITests targets in a DRY way.

Update cocoapods instructions

---

Quick/QuickSpec.m
QuickTests/FunctionalTests/SharedExamplesTests+ObjC.m

When calling `itBehavesLike` multiple times from within the same ObjC spec, the `sharedExamples` gets always called with the same context. Problem is, that the dynamically generated selector for the instance of the `Example` is always the same same. see c5675e53f55ab05a0e861556ad03f012b9ce4d4a
This PR tries to fix this by adding more unique properties (filename and line number) to the generated selector name. see 563f61570ce3b3cfce7fa5de6e566b5d6c767913

Shared examples with different context

---

Quick/Callsite.swift
Quick/DSL/DSL.swift
Quick/DSL/World+DSL.h
Quick/DSL/World+DSL.swift

Lines are always greater than zero so they can be unsigned - just to match `XCTests`, because they are also using unsigned ints,

Switch LineNumber argument to an unsigned int

---

Quick/ExampleGroup.swift

Building with Xcode 7b6 produced the following error in a 3 places:
```
error: 'extend' has been renamed to 'appendContentsOf'
examples.extend(group.examples)
^~~~~~
appendContentsOf
Swift.RangeReplaceableCollectionType:3:17: note: 'extend' has been explicitly marked unavailable here
mutating func extend<S : SequenceType where S.Generator.Element == Generator.Element>(newElements: S)
^
```

Fix compile issue on Xcode 7b6

---

circle.yml

Circle CI recently announced support for XCode 7.0
https://twitter.com/circleci/status/644589240907489280
It may not be 100% stable yet, but as the swift-2.0 branch is being ignored anyway, I think it's better than what we have now.

Changes XCode version on Circle CI to be 7.0

---

QuickFocusedTests/FocusedTests+ObjC.m
QuickTests/FunctionalTests/AfterEachTests+ObjC.m
QuickTests/FunctionalTests/AfterSuiteTests+ObjC.m
QuickTests/FunctionalTests/BeforeEachTests+ObjC.m
QuickTests/FunctionalTests/BeforeSuiteTests+ObjC.m
QuickTests/FunctionalTests/FailureTests+ObjC.m
QuickTests/FunctionalTests/FailureUsingXCTAssertTests+ObjC.m
QuickTests/FunctionalTests/ItTests+ObjC.m
QuickTests/FunctionalTests/PendingTests+ObjC.m
QuickTests/FunctionalTests/SharedExamples+BeforeEachTests+ObjC.m
QuickTests/FunctionalTests/SharedExamplesTests+ObjC.m

When investigating #373, I ran into an issue in which
`+[XCTestCase testInvocations]` would return the **wrong set of
invocations** when two test cases shared the same class name!
This sounds absolutely insane, but it's true! Notice that if you define
two test cases, one in Swift and one in Objective-C, but with the same
name, their test methods are grouped in Xcode's test navigator:
The test case class names don't collide when defined in Swift and
Objective-C respectively, but end up behaving very erratically. To
prevent this issue, make sure Objective-C and Swift tests are named
"namespaced" by affixing "_ObjC" to Objective-C test classes.
This probably deserves an Apple radar.

QuickTests: Suffix Objective-C tests with "_ObjC"

---

.gitignore

Added `Carthage/Build` to gitignore to solve the following problem with Carthage.
After running `carthage update --use-submodules` or `carthage bootstrap --use-submodules`, untracked contents are detected by Git because Quick does not ignore `Carthage/Build` directory. The directory has to be removed not to be committed.
```
$ git status
On branch master
Changes not staged for commit:
modified:   Carthage/Checkouts/Quick (untracked content)
```
Added `Carthage/Build` to gitignore. The added part of gitignore was taken from the following example.
https://github.com/github/gitignore/blob/master/Swift.gitignore
This modification has no impact to CocoaPods users. With the gitignore, Carthage users will be more comfortable to use Quick in their projects.

Add Carthage/Build to gitignore for better support of Carthage

---

Quick/Quick.h

This seems to be the root cause for new projects created in Xcode 7.1
to report "Include of non-modular header inside framework Module
'Quick'".
Infer: It seems like the swift compiler in Xcode 7.1 now prevents
non-modular includes in umbrella header files. The public headers are
assumed to be imported in modules.
Context: #395

Remove public headers from umbrella header

---

.travis.yml
Rakefile
circle.yml

See https://github.com/Quick/Quick/issues/389
For some reason my CircleCI setup has decided that I cannot run Xcode tests anymore, so I thought I might as well open the PR anyway and see if the tests will run for the Quick organization.

Add xctool tests to CI

---

Quick.xcodeproj/project.pbxproj
Quick/DSL/DSL.swift
Quick/DSL/World+DSL.swift
Quick/Example.swift
Quick/QuickSpec.m
Quick/World.swift
QuickTests/FunctionalTests/DescribeTests.swift

Add a (hopefully) more informative error message when crashing in `describe` to make [crashes like this one](https://github.com/Quick/Nimble/issues/219) more straightforward. From what I can tell the only time the current example group can be `nil` is if the root group was never instantiated.
Includes some minor code changes that don't affect behavior as well.

add descriptive error when describe is used out of context

---

Documentation/QuickExamplesAndGroups.md

I propose adding this sentence after spending 15+ mins trying to work out if `context` added any new syntax or behaviour beyond `describe`. Digging into the source showed that it is a synonym. I tried to make my addition match the tone of the document (_which is wonderfully written for a broad audience btw!_).

Noted that `context` is a synonym for `describe`

---

Quick.xcodeproj/project.pbxproj
QuickTests/FunctionalTests/ContextTests.swift
Sources/Quick/DSL/DSL.swift
Sources/Quick/DSL/World+DSL.swift
Sources/Quick/Example.swift
Sources/Quick/ExampleGroup.swift
Sources/Quick/Hooks/ExampleHooks.swift
Sources/Quick/Hooks/HooksPhase.swift
Sources/Quick/Hooks/SuiteHooks.swift
Sources/Quick/World.swift
Sources/QuickTests/FunctionalTests/AfterEachTests.swift
Sources/QuickTests/FunctionalTests/BeforeEachTests.swift
Sources/QuickTests/FunctionalTests/ContextTests.swift
Sources/QuickTests/FunctionalTests/DescribeTests.swift
Sources/QuickTests/FunctionalTests/ItTests.swift
Sources/QuickTests/FunctionalTests/SharedExamplesTests.swift

This is a crack at solving #362. 
I spent a bit of time trying to use the properties that existed on World to reliably deduce where the current DSL function lied contextually. Unfortunately, doing so made it tough to produce exact error messages for, say, a 'beforeEach' within a 'describe' vs one within a 'context', so I had to switch gears. Overall, I'm happy with what resulted -- a new property on World to track the containing DSL function of the executing function, and a helper method that manages the logic of the throwing the error. 
Admittedly, I'm concerned that managing the 'currentExampleContextDescriptor' property might be a little clunky and hard to intuit to someone walking into the code for the first time. I'd love some suggestions here if you agree that it could be better …

Error out with more specific messages when misusing DSL functions

---

.travis.yml
Quick.xcodeproj/project.pbxproj
Rakefile
Sources/Quick/NSString+QCKSelectorName.m
Sources/Quick/QuickSpec.m
Sources/QuickTests/FunctionalTests/ItTests+ObjC.m
Sources/QuickTests/FunctionalTests/ItTests.swift
Sources/QuickTests/Helpers/QuickSpec+QuickSpec_MethodList.h
Sources/QuickTests/Helpers/QuickSpec+QuickSpec_MethodList.m
Sources/QuickTests/Helpers/QuickTestsBridgingHeader.h

I followed the approach suggested in issue #392's thread, using an `NSSet` to track the existing unique selector names and append a number onto the end of additional ones to keep them unique.

Shorten selector names

---

circle.yml
script/travis-install-osx
script/travis-script-osx

This PR completes the work started in https://github.com/Quick/Quick/pull/417.
The issues with `xctool` that prevented us from running the tests for the OS X on CI have been fixed by a recent release. We're good to go :rocket: 
**Note** the tests are failing on Linux, but that's unrelated with `xctool`.

Enable xctool for OS X target in CI 

---

Sources/Quick/Example.swift
Sources/Quick/World.swift

Fixes #482.
I had really been hoping to introduce test coverage around this (cf. [here](https://github.com/Quick/Quick/blob/master/Sources/QuickTests/FunctionalTests/AfterSuiteTests.swift#L41)), but came to the conclusion that it would require more extra infrastructure in the test suite (because the assertion would have to run *after* Quick's test suite finishes, clearly) than I have time to build right now.

Fix the test counting used to determine when to execute `afterSuite` hooks

---

Quick.xcodeproj/project.pbxproj
Sources/QuickTests/Helpers/QCKSpecRunner.m
Sources/QuickTests/Helpers/XCTestObservationCenter+QCKSuspendObservation.h
Sources/QuickTests/Helpers/XCTestObservationCenter+QCKSuspendObservation.m

When I updated the Nimble submodule to fix compilation on Xcode 7.3, I discovered that the changes made in https://github.com/Quick/Nimble/pull/244 break the Quick tests because of the way that we use `+[XCTestObservationCenter _suspendObservationForBlock:]` to enable running `XCTestSuite` instances during the middle of an existing run. The problem is that Nimble now relies on a test observer of its own in order to be able to report failures to XCTest (see the CI failure [here](https://travis-ci.org/Quick/Quick/jobs/109524574)). 
This PR changes the `QCKSpecRunner` behavior so that, instead of using private API on XCTestObservationCenter, it swizzles public methods to keep track of XCTest's own observers, then temporarily removes them from the center to implement the suspension behavior. …

Adjust the way that test observation suspension works.

---

README.md

Also is there a reason why the example points to a specific Nimble version instead of ~>

Updated Nimble to 3.1.0 in Podfile example

---

.travis.yml
Sources/Quick/DSL/DSL.swift
circle.yml
script/travis-install-osx

General changes to get Quick to build on Xcode 7.3 without warnings.
- Replace deprecated `__FILE__` and `__LINE__` with `#file` and `#line`, respectively
:warning: These changes require Xcode 7.3 and Swift 2.2 or better.
I didn't update the Nimble submodule yet, but can once Quick/Nimble#269 is merged.

Swift 2.2 and Xcode 7.3

---

Sources/Quick/QuickSpec.h

QuickSpec.spec() is instance method.

Fix example description in QuickSpec.h

---

Sources/Quick/QuickSpec.h

Wrapped example spec with `@code` and `@endcode` to preserve formatting in help callout.

Format example spec in doc comment

---

Documentation/en-us/QuickInObjectiveC.md

We have a long-lived project with both Objective-C and Swift tests. The Ojective-C specs use Specta, which conflicts with Quick. For some reason no matter what header I add the `QUICK_DISABLE_SHORT_SYNTAX` macro to, it does not apply. The only way I was able to get it to work was by creating the macro in the test target's build configuration.
This PR just adds instructions for how to do that.

Adds instructions for putting the QUICK_DISABLE_SHORT_SYNTAX macro in project config

---

Quick.xcodeproj/project.pbxproj
Sources/Quick/DSL/World+DSL.swift
Sources/Quick/QuickSpec.m
Sources/Quick/World.h
Sources/Quick/World.swift
Sources/QuickTests/FunctionalTests/CrossReferencingSpecs.swift
Sources/QuickTests/main.swift

This could occur because `+[QuickSpec initialize]` was being called recursively when a new `QuickSpec` subclass was being referenced for the first time while another spec was in the middle of gathering examples.
Fixes #506, #515

Fix crash caused by currentExampleGroup being unexpectedly nil

---

Quick.xcodeproj/project.pbxproj

Quick cannot currently be used on tvOS devices since bitcode is required but the XCTest framework does not contain bitcode. By changing the `SDKROOT` to `appletvsimulator` on the Quick-tvOS target, this has no effect on simulator builds, but provides an immediate and much more informative error on device builds instead of linker errors.
Carthage currently cannot build Quick since it attempts to build for both the simulator and device (#422). I've proposed a fix for this in Carthage/Carthage#1268 which keys off of the `ENABLE_BITCODE` setting being `NO` to skip building for the device since bitcode is required to build for tvOS devices. This setting has no effect on simulator builds where bitcode is not used.

Better handling of unsupported tvOS devices

---

.travis.yml
script/travis-script-osx

This is my attempt at implementing option 2 as discussed at #520. [Here](https://travis-ci.org/briancroom/Quick/builds/125160996) is the build Travis made against this commit already, where it can be seen how the `xctool` job failed while the Linux and basic OS X jobs passed, as expected.

Split out a separate Travis job for testing xctool

---

.travis.yml
Gemfile
Gemfile.lock
Rakefile
script/travis-script-osx

* Created a new build process just for lint (similar approach used in https://github.com/Quick/Nimble/pull/288)
* ~~Travis claims that [cocoapods is already installed on OS X instances](https://docs.travis-ci.com/user/osx-ci-environment#Gems-in-the-global-gem-set), so I didn't bother using `gem` or `bundle` to install it.~~
* Added a task `podspec:lint` on Rakefile
* Changed `travis-script-osx` to run either `podspec:lint` or `tests` (not sure if that's the best approach tho)
This fixes #521

Adds podspec lint on CI

---

Quick.podspec

Continued from #529 and #530 
As pointed out by @briancroom in #530, podspec needs a Search Path in order to locate XCTest.

Adds search path in podspec for XCTest

---

Quick.podspec

As called out in #531, `xcconfig` is deprecated and `user_target_xcconfig` should be used instead.

Replaces deprecated property in podspec (changes xcconfig to user_target_xcconfig)

---

Quick.xcodeproj/project.pbxproj

Xcode 8 claims that `appletvsimulator` is not found for the setting. Fixes #548.

Use `appletvos` for `SDKROOT` build setting in Quick-tvOS

---

Documentation/en-us/TestUsingTestDoubles.md

I made some improvements to the `TestUsingTestDoubles.md` file. The grammar is better and examples are more consistent with the words. This [Stackoverflow issue](http://stackoverflow.com/questions/3622455/what-is-the-purpose-of-mock-objects) helped me.

Fix grammar and provide more detailed descriptions

---

README.md

We used to have a status badge for Circle CI, not sure why it was removed.
Added the Travis one because it's seems to be most updated one.

Adds Travis CI status to README

---

Documentation/en-us/InstallingQuick.md

There is also a section on using Swift 1.2 which I'm not sure if it's worth keeping (maybe the versions needed for 1.2 should be added on README?)
Thoughts?

Adds link to Swift version in installation doc

---

Documentation/en-us/InstallingQuick.md

This PR removes a outdated section about Swift 1.2  in InstallingQuick.md
Related: https://github.com/Quick/Quick/pull/617

Remove outdated doc about swift 1.2

---

README.md

I added a section about Who uses Quick to the README. This is related to #570.

Add section about Who uses Quick

---

Documentation/en-us/SharedExamples.md

It was not fully up-to date for Swift 3 GM and as such would fail to compile if compiled as-is.

Update function prototype in docs for shared examples

---

Package.swift

See also https://github.com/ReactiveCocoa/ReactiveSwift/pull/68.

[Package.swift] Don't lock Nimble version to exact v5.0.0

---

.Package.test.swift
Package.swift
Rakefile

We still run `swift test` on CI using separated `.Package.test.swift`.
This is the same as https://github.com/Carthage/Commandant/pull/83.

[SwiftPM] Remove test dependencies from `Package.swift`

---

.github/ISSUE_TEMPLATE
.github/PULL_REQUEST_TEMPLATE

Fixes #635.
Open for feedback. Also needs copied to Nimble after this gets merged.

Add github templates

---

Quick.xcodeproj/project.pbxproj

Fix #648. Warning messages should be compressed even if SwiftLint is not installed.

[SwiftLint] Compress install warning messages

---

Sources/Quick/World.swift

Changed the return type of `SharedExampleContext ` from `NSDictionary` to `[String: Any]`.
This fixes issue #653.

Using `[String: Any]` as return type of `SharedExampleContext`

---

Sources/QuickObjectiveC/QuickSpec.m

The implementation above uses a block that return void.
Probably the code from XCTestCase doesn't try to inspect the return
value, but it is probably better to include the right type
information just in case.
No new tests or documentation. The change is internal and should not affect the current behaviour. Test pass.

Change test method encoding to return void.

---

Sources/QuickObjectiveC/QuickSpec.m

Some unused code was present in the Objective-C QuickSpec class. The resulting `sanitizedFileName` was used, but then stop being used in 08b4bee51441ee64ab91794bb48076f26a9b0ef8.
The code should work exactly the same as before (maybe slightly faster). No tests nor documentation, but the change doesn’t modify the behaviour.

Remove unused code.

---

Sources/Quick/ExampleGroup.swift

[SwiftLint] Correct empty_parentheses_with_trailing_closure rule

---

Documentation/en-us/SettingUpYourXcodeProject.md

Mention filing a radar that's a duplicate to an existing radar bug
(26152293) to help promote this feature for Xcode.
Addresses concerns in #667.

Add note to file radar for Xcode Integration

---

.swiftlint.yml

There is no violations for the rules. Related to #641.

[SwiftLint] Enable some disabled rules

---

Sources/Quick/DSL/DSL.swift
Sources/Quick/Hooks/ExampleHooks.swift
Sources/Quick/QuickSpec.swift
Tests/QuickTests/QuickTestHelpers/XCTestCaseProvider.swift

[SwiftLint] Suppress unused closure parameter and colon violation

---

Sources/Quick/QuickMain.swift

Just some misaligned function parameters in one file generating extra warnings.

Make Quick SwiftLint compatible #641

---

Documentation/en-us/SharedExamples.md

`someting` -> `something`
Found while working on #681

Fixes typo in SharedExamples.md

---

Sources/QuickObjectiveC/QuickSpec.m

This eliminates Objective-C's associated objects usage and overriding `-setInvocation:`.
There should be no functional changes.

[QuickSpec] Track the current example within `imp_implementationWithBlock`

---

Sources/Quick/Example.swift

Due to the fact that world.includedExamples is a computed property that does  a filter on all the tests, performing `numberOfExamplesRun >= world.includedExampleCount` is not very efficient
with a very large number of tests.
This patch caches the result of world.includedExampleCount and uses the cached value to perform the comparison.
Fix #696

Cache the included example count on Example.run()

---

Quick.xcodeproj/project.pbxproj
Quick.xcodeproj/xcshareddata/xcschemes/Quick-iOS.xcscheme
Quick.xcodeproj/xcshareddata/xcschemes/Quick-macOS.xcscheme
Quick.xcodeproj/xcshareddata/xcschemes/Quick-tvOS.xcscheme

close #693 
- SwiftLint will be execute only in Test(It isn't executed in Build).
- delete SwiftLint Run Script Phase from Quick-macOS/Quick-iOS/Quick-tvOS target.
- add Aggregate to execute SwiftLint Run Script
The reason why I submit this PR is written on #693, so please refer it.

fix issue 693, Fail compiling Quick using Carthage because of SwiftLint

---

Quick.xcodeproj/project.pbxproj
Sources/Quick/Behavior.swift
Sources/Quick/DSL/DSL.swift
Sources/Quick/DSL/World+DSL.swift
Tests/QuickTests/QuickFocusedTests/FocusedTests.swift
Tests/QuickTests/QuickTests/Fixtures/FunctionalTests_BehaviorTests_Behaviors.swift
Tests/QuickTests/QuickTests/FunctionalTests/BehaviorTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/PendingTests.swift

This introduces a base generic behavior definition which can be extended with a specified context type.
Currently, shared assertions implementation using "shared examples" suffers from two drawbacks:
- Defined in `QuickConfiguration` subclass. A file that initially intended for configuration how Quick behaves, "shared examples" are added here to allow their discovery during setup time.
- Receives a context of `[String: Any]`, which is string-typed and erase any type information of the context elements.
The proposed solution is to introduce `Behavior<Context>` which will address these issues by allowing user to define subclasses for each "shared example" with a specific context type and a similar structure to `QuickSpec`
The example below demonstrates how it might be used:
```
import Quick …
```

Introduce `Behavior<Context>`

---

.Package.test.swift
.travis.yml
Package.swift

See https://github.com/Quick/Nimble/pull/431.
Ideally we should wait for the next Nimble patch release before merging (to avoid pinning `Externals/Nimble` to a branch).

Enable Swift 3 compatibility mode under Swift 4

---

Sources/Quick/Configuration/Configuration.swift
Sources/Quick/Configuration/QuickConfiguration.swift
Sources/Quick/DSL/World+DSL.swift
Sources/Quick/ErrorUtility.swift
Sources/Quick/NSBundle+CurrentTestBundle.swift
Sources/Quick/NSString+C99ExtendedIdentifier.swift
Sources/Quick/QuickSelectedTestSuiteBuilder.swift
Sources/Quick/QuickSpec.swift
Sources/Quick/QuickTestSuite.swift
Sources/Quick/World.swift
Tests/QuickTests/QuickTestHelpers/XCTestCaseProvider.swift
Tests/QuickTests/QuickTests/FunctionalTests/AfterEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/BeforeEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/BehaviorTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/ContextTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/DescribeTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/SharedExamplesTests.swift

Use `#if os(macOS) || os(iOS) || os(tvOS) || os(watchOS)` instead.
See #718 for the details.

Avoid using `#if _runtime(_ObjC)` check

---

Tests/QuickTests/QuickTests/FunctionalTests/AfterEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/BeforeEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/BehaviorTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/ContextTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/DescribeTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/SharedExamplesTests.swift

`#if !SWIFT_PACKAGE` should be sufficient for those cases.
Just a minor refactoring.

[gardening] Remove redundant OS checks

---

Tests/QuickTests/QuickTests/FunctionalTests/AfterEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/BeforeEachTests.swift

Cherry-picked some commits from #724. Related to #641.
Thanks to @ecylo for the original efforts!

Enum cases should be lower camel case

---

Sources/Quick/Configuration/QuickConfiguration.swift

Hey guys! First of all thank you so much for your constant work on Quick/Nimble, really appreciate that. Recently I was working extensively with SPM and wanted to try both Quick/Nimble with SPM. I encountered a runtime crash (bad access) on [this line](https://github.com/sunshinejr/Quick/blob/master/Sources/Quick/Configuration/QuickConfiguration.swift#L29).
My environment:
- SPM/Swift 4.0
- PackageDescriptionV4
- Quick version 1.1.0
Seems like the forcecast on the `superclass` type was creating a crash whenever there was no superclass. I've changed it to be safer so whenever there is no superclass, it will just skip it. If the code style is different from what you have right now, feel free to correct me/change it.
Cheers!

Fix SPM integration.

---

Documentation/en-us/TestingApps.md
Quick.xcodeproj/project.pbxproj
Sources/QuickObjectiveC/QuickSpec.h
Sources/QuickObjectiveC/QuickSpec.m
Tests/QuickTests/QuickTests/FunctionalTests/CurrentSpecTests.swift

This provides a static `QuickSpec.current()` method which allows specs to get a reference to the currently executing `QuickSpec`, which is essential for using XCTest expectations.
This is an updated version of #331. It fixes #330 and #578.
There was a lot of high-minded discussion back then about different approaches to this problem, and indecision lead to nothing happening. This PR is an attempt to nudge Quick toward resolving the issue. Two arguments in favor of this solution:
- It’s simple.
- It works. [Siesta](https://github.com/bustoutsolutions/siesta) has happily been using this on a fork for over a year.
If the Quick team is willing to accept this change, I’m happy to add tests and/or docs to the PR. Let me know.

Expose current spec for XCTest expectations

---

Sources/Quick/Configuration/QuickConfiguration.swift
Sources/Quick/QuickSpec.swift

Hey guys! 
Here with another SPM fix. This time for Swift 4 specifically. Seems like [last time](https://github.com/Quick/Quick/pull/746) I was using Swift 3.2 for Quick, even though I've built it in with SPM/Swift4. This time, when switching to Swift 4.0 on Quick, I've seen an error due to `XCTest.defaultTestSuite()` change. Basically in Swift 3.* `XCTest.defaultTestSuite()` is a method and in Swift 4.* it is a [variable](https://developer.apple.com/documentation/xctest/xctestcase/1496289-defaulttestsuite), making the build fail. 
I've fixed this one using `if swift(>=4)`, but I'm all ears if you have another fix in mind.
Also, this could appear everywhere with Swift 4, not only SPM, but SPM was the only one I’ve tested.
Cheers!

Fix XCTest override error on SPM/Swift4

---

Documentation/en-us/NimbleAssertions.md
Documentation/en-us/QuickExamplesAndGroups.md
Documentation/ja/NimbleAssertions.md
Documentation/ja/QuickExamplesAndGroups.md
Documentation/ko-kr/NimbleAssertions.md
Documentation/ko-kr/QuickExamplesAndGroups.md
Documentation/zh-cn/NimbleAssertions.md
Documentation/zh-cn/QuickExamplesAndGroups.md

This PR fixes two minor issues in the docs:
- Use modern Swift-styled enum case names
- Remove a force-unwrapping where the definition itself is already implicitly unwrapped

Minor documentation fixes

---

Sources/QuickObjectiveC/DSL/World+DSL.h
Sources/QuickObjectiveC/QuickSpec.m
Sources/QuickObjectiveC/World.h
Sources/QuickObjectiveC/XCTestSuite+QuickTestSuiteBuilder.m

This PR fixes #780 in relation to Cocoapods 1.5. In this new version of Cocoapods, some things have changed in how header files are found. The recommendation from the Cocoapods team seems to be to change the imports to this:
```
#if __has_include("Quick-Swift.h")
#import "Quick-Swift.h"
#else
#import <Quick/Quick-Swift.h>
#endif
```
I tested this against my app and it seems to work fine with no side-effects.

Support Cocoapods 1.5

---

Documentation/en-us/SharedExamples.md

`SharedExampleContext` should be marked with `@escaping` in Swift example code.

Add @escaping to Swift example

---

Quick Templates/Quick Configuration Class.xctemplate/Objective-C/___FILEBASENAME___.h
Quick Templates/Quick Configuration Class.xctemplate/Objective-C/___FILEBASENAME___.m
Quick Templates/Quick Configuration Class.xctemplate/Swift/___FILEBASENAME___.swift
Quick Templates/Quick Spec Class.xctemplate/Objective-C/___FILEBASENAME___.m
Quick Templates/Quick Spec Class.xctemplate/Swift/___FILEBASENAME___.swift

Templates had added Xcode Header in #540 , but it was not aligned.
---
BTW, In recent Xcode' template can be defined header with only `// ___ FILEHEADER___`.
It seemed to be a preferable fix, but I don't know whether it is available in past Xcode  versions.
so I fixed only the space.

Add left alignment spaces for copyright in template files

---

Quick.xcodeproj/project.pbxproj
Tests/QuickTests/QuickTests/Helpers/QuickSpec+QuickSpec_MethodList.h
Tests/QuickTests/QuickTests/Helpers/QuickSpec+QuickSpec_MethodList.m

I'll say that this is a preliminary task for fixing #785.

[1.x] `QuickSpec+QuickSpec_MethodList` should be in the test targets, not in the library targets

---

.travis.yml
Rakefile
Sources/Quick/NSString+C99ExtendedIdentifier.swift
Sources/QuickObjectiveC/QuickSpec.m

~~Extension methods or properties for NSObject subclasses are somehow invisible from the Objective-C runtime on static linking, so let's make a wrapper class.~~
Extension methods or properties for NSObject subclasses are invisible from the Objective-C runtime on static linking unless the consumers add `-ObjC` linker flag, so let's make a wrapper class to mitigate that situation.
Fixes #785.

[1.x] Fix unrecognized selector crash on static linking

---

Dangerfile

Contributing to CONTRIBUTING.md should be good.
Addresses https://github.com/Quick/Quick/pull/767#issuecomment-363943363.

[Danger] Remove CONTRIBUTING.md from SDM_DANGER_IMMUTABLE_FILES

---

Sources/Quick/Example.swift

If you select only one test case to run in xcode test navigator, the test can fail with error:
```
'NSInternalInconsistencyException', reason: ''beforeEach' cannot be used inside 'it', 'beforeEach' may only be used inside 'context' or 'describe'. ', userInfo: '(null)'
```
During test run `world.currentExampleMetadata` is set to current example, but it's never cleared. So once an example runs, no `beforeEach` can be called after it.
Before the example finishes running, clear Clear world.currentExampleMetadata.
Example.run()

Fix NSInternalInconsistencyException when running a test from test navigator

---

Sources/Quick/Example.swift

Cherry-picks #716.
This actually fixes Xcode 10's parallel testing problem: https://github.com/Quick/Quick/issues/801#issuecomment-402518207.

[1.x] clear world.currentExampleMetadata after example run

---

Package.resolved

https://github.com/Quick/Nimble/releases/tag/v7.1.3
For `1.x-branch`: https://github.com/Quick/Quick/pull/807

Update Nimble to 7.1.3

---

Documentation/ko-kr/BehavioralTesting.md

Found a typo while reading docs
it says babana, I changed it to banana
바바나              ->            바나나

Simple typo correction in a KR doc

---

Quick.xcodeproj/project.pbxproj

`Headers` should be placed before `Sources` to match with the Xcode 10's project template.
Fixes #799.
For CocoaPods users, they need to update `xcodeproj` gem: https://github.com/CocoaPods/Xcodeproj/blob/master/CHANGELOG.md#160-2018-08-16
> Create new targets with the Xcode 10 default ordering for build phases.

Xcode 10: Adjust Build Phases order

---

Sources/Quick/Behavior.swift

This PR will suppress the following warning:
```
Pods/Quick/Sources/Quick/Behavior.swift#L7: static declarations are implicitly ‘final’; use ‘public’ instead of ‘open’ 
open static var name: String { return String(describing: self) }
```

Fix Xcode 10 warning

---

Dangerfile

Danger only considers Objective-C header files and Swift files for the warning.
Closes #689

Issue-689:  Improve QuickBot lint warning

---

Sources/Quick/Callsite.swift
Sources/Quick/Configuration/Configuration.swift
Sources/Quick/Configuration/QuickConfiguration.swift
Sources/Quick/DSL/World+DSL.swift
Sources/Quick/ErrorUtility.swift
Sources/Quick/Example.swift
Sources/Quick/ExampleMetadata.swift
Sources/Quick/Filter.swift
Sources/Quick/NSBundle+CurrentTestBundle.swift
Sources/Quick/NSString+C99ExtendedIdentifier.swift
Sources/Quick/QuickMain.swift
Sources/Quick/QuickSelectedTestSuiteBuilder.swift
Sources/Quick/QuickSpec.swift
Sources/Quick/QuickTestSuite.swift
Sources/Quick/World.swift
Tests/QuickTests/QuickTestHelpers/XCTestCaseProvider.swift
Tests/QuickTests/QuickTests/FunctionalTests/AfterEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/BeforeEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/BehaviorTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/ContextTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/DescribeTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/SharedExamplesTests.swift

https://github.com/apple/swift-evolution/blob/master/proposals/0075-import-test.md
There should be no behavioral change, just replacing `#if os(macOS) || os(iOS) || os(tvOS) || os(watchOS)` with `#if canImport(Darwin)`.

Use `#if canImport` implemented in Swift 4.1 (SE-0075)

---

Package@swift-4.swift

This would make it possible for Quick 1.x to be consumed with Swift 5's SwiftPM which does not support Swift 3 mode anymore.

[1.x][SwiftPM] Update swiftLanguageVersions to 4 for Package@swift-4.swift

---

Package.swift
Package@swift-4.2.swift

As upgrading to Swift 5, without having `platforms` the default deployment target is set to the latest version of each OS. It causes a compile error.
* Add `platforms`
* Add `.v5` to `swiftLanguageVersions`

[SwiftPM] Update Package.swift to support Swift 5

---

.travis.yml
Quick.xcodeproj/project.pbxproj
Sources/Quick/QuickSpec.swift
Tests/LinuxMain.swift
Tests/QuickTests/QuickTests/FunctionalTests/CurrentSpecTests.swift

Ref: #645, #848
This is a preparation for #680 which uses `QuickSpec.current`.

Support QuickSpec.current on Linux

---

Tests/QuickTests/QuickTestHelpers/SpecRunner.swift
Tests/QuickTests/QuickTestHelpers/TestRun.swift
Tests/QuickTests/QuickTestHelpers/XCTestCaseProvider.swift

Since they are in a test target, they don't need to be public.

[refactoring] Make test helpers non-public (internal)

---

Rakefile

Otherwise CI jobs report success even if `xcodebuild` fails.

[CI] Propagate xcodebuild errors correctly

---

Package.swift
Tests/QuickTests/QuickTests/Helpers/QuickSpec+MethodList.swift
Tests/QuickTests/QuickTests/Helpers/QuickSpecRunner.swift
Tests/QuickTests/QuickTests/Helpers/XCTestObservationCenter+QCKSuspendObservation.swift

Instead let's conditionally compile them.
In a future, I'd like to reuse them in SwiftPM builds on Darwin.
Refs: #861, #860, #859, #858

[SwiftPM] Don't exclude QuickTests/Helpers

---

Sources/Quick/QuickSpec.swift

[refactoring][QuickSpec.swift] Use `World.performWithCurrentExampleGroup`

---

Documentation/en-us/InstallingQuick.md
README.md

This documents support for the new SwiftPM based dependency manager [Accio](https://github.com/JamitLabs/Accio).
Please note that this project is part of Accio's official [integration tests](https://github.com/JamitLabs/Accio/tree/work/1000-frameworks/Demo/Shared/AppDependencies) within the [Demo project](https://github.com/JamitLabs/Accio/tree/work/1000-frameworks/Demo).

Document support & installation via Accio

---

Sources/Quick/QuickSpec.swift
Sources/QuickSpecBase/QuickSpecBase.m
Sources/QuickSpecBase/include/QuickSpecBase.h

[refactoring] Remove _QuickSelectorWrapper and use String instead

---

Sources/Quick/QuickSpec.swift
Sources/Quick/World.swift

[refactoring] Reduce uses of AnyClass, replace them with QuickSpec.Type where possible

---

Quick.xcodeproj/project.pbxproj
Sources/QuickObjectiveC/Configuration/QuickConfiguration.m
Sources/QuickObjectiveC/QuickSpec.m
Tests/LinuxMain.swift
Tests/QuickTests/QuickTests/FunctionalTests/SubclassOfSubclassWithStructPropertyTests.swift

Fixes #853.
This fixes a runtime crash when a subclass of QuickSpec is subclassed and the subclass has a Swift struct property. This avoids nested calls of `+[QuickConfiguration initialize]` and `objc_getClassList`.

Don't call `+[QuickConfiguration initialize]` method manually

---

Sources/Quick/Example.swift
Sources/Quick/World.swift

This makes it easy to create separate World instances when running additional test suites.

[refactor] Convert some global variables into World's states

---

Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift
Tests/QuickTests/QuickTests/Helpers/QuickSpec+MethodList.swift
Tests/QuickTests/QuickTests/Helpers/XCTestObservationCenter+QCKSuspendObservation.swift

[refactoring] Remove unnecessary `!SWIFT_PACKAGE` conditions

---

Sources/Quick/Behavior.swift

The PR is a byproduct of [my article](https://vojtastavik.com/2019/07/22/advanced-testing-using-behavior-in-quick/) about using `Behavior` in Quick.
I believe the `name` variable of `Behavior` should be `open` so it's possible to override it and provide custom name, if needed.

Make `name` variable of `Behavior` open

---

Quick.xcodeproj/project.pbxproj
Sources/QuickObjectiveC/QuickSpec.m
Tests/QuickTests/QuickTests/FunctionalTests/QuickSpec_SelectedTests.swift

This PR fixes the regression introduced in a3ece4f. Closes #891 
The `defaultTestSuite` method wasn't called when the 'Selected tests' type of test suite was executed. This caused the `spec` method not being invoked and the examples for the given class were never built.
This PR changes the behaviour and introduces a new `buildExamplesIfNeeded` method. This method can be called safely multiple times. We call it from both the `defaultTestSuite` and `testInvocations` methods. This ensures the examples are built properly no matter which method is called (or in which order).

Fix empty 'Selected tests' suites

---

Sources/Quick/ExampleGroup.swift
Sources/QuickObjectiveC/QuickSpec.m
Tests/QuickTests/QuickFocusedTests/FocusedTests.swift

Ref: https://github.com/Quick/Quick/pull/901#issuecomment-530600416
Based on #916 with Linux build failure fix.

Fix crash with combination of focused tests and shared examples registered in a unfocused spec class

---

Documentation/en-us/README.md
Documentation/en-us/SharedExamples.md
Sources/Quick/Behavior.swift

I use Quick for several years and recently I accidentally discovered `Behavior`. I really love the feature! I realized that I didn't know about it because it's not mentioned anywhere in the documentation.
This PR adds another option to the `Reducing Test Boilerplate` documentation presenting an alternative solution using `Behavior<Context>`.

Add documentation for `Behavior<Context>`

---

Sources/Quick/World.swift
Sources/QuickObjectiveC/QuickSpec.m

This commit fixes the crash reported in https://github.com/Quick/Quick/pull/901#issuecomment-530600416 .

[refactoring] Build examples only for classes without root example group

---

Sources/Quick/Configuration/Configuration.swift

- none
- 4 functions' comments is update
- Why was this change introduced?
- to fix the typo from mulitple to multiple

fix typo in Configuration.swift for "Mulitple"

---

.github/workflows/ci.yml
.travis.yml
Rakefile

Due to https://github.blog/changelog/2019-11-06-github-actions-macos-virtual-environment-updated-to-catalina/
Ref: https://github.com/Quick/Nimble/pull/712

[CI] Fix GitHub Actions breakage and restore Travis build matrix for older Xcode versions

---

Sources/Quick/DSL/DSL.swift
Tests/QuickTests/QuickTests/FunctionalTests/PendingTests.swift

Disabling a `describe` or a `context` by prefixing them with x, like `xdescribe` and `xcontext` would generate a compilation error complaining about a missing flags param, contrary to `it`/`xit`, `fdescribe` or `fcontext`.
With this PR the following will compile:
```swift
xdescribe("some description") {
xcontext("some context description") {
it("will not be run...") { fail() }
}
}
```
This PR adds a default value to the flags parameter in DSL.swift and also corresponding tests in PendingTests.swift.

Added empty default flags to xdescribe and xcontext

---

Quick Templates/Quick Spec Class.xctemplate/Objective-C/___FILEBASENAME___.m

I change the OC Quick Template, from this issue https://github.com/Quick/Nimble/issues/642
The  Quick Spec Class.xctemplate OC file ___FILEBASENAME___.m
https://github.com/Quick/Nimble/issues/642
- [] Does this break the public API (Requires major version bump)?
- [] Is this a new feature (Requires minor version bump)?

Update the Objective-C QuickSpec template to use modules (semantic import)

---

Documentation/en-us/InstallingQuick.md
Documentation/ja/InstallingQuick.md
Documentation/ko-kr/InstallingQuick.md
Documentation/zh-cn/InstallingQuick.md

Resolves #723.
https://help.apple.com/xcode/mac/11.4/#/devf5378fca9 is the new location.

Fix Xcode documentation link of how to create xcworkspace

---

Sources/Quick/Configuration/QuickConfiguration.swift

There is a possible crash in `QuickConfiguration` that may occur during race conditions with other threads because of the number of classes returned by `objc_getClassList` changes between calls. That causes `EXC_BAD_ACCESS` crash during accessing out of the bounds memory by `class_getSuperclass` if malloc guards enabled in Xcode scheme diagnostics tab.
I inserted a `sleep` between calls and prints so it became obvious:
```
classesCount: 29605
...
classesCount: 29634
```
```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY
Application Specific Information:
This process is running with libgmalloc.dylib (GuardMalloc) which may have forced the crash due …
```

Fixes race conditions in QuickConfiguration

---

.swiftlint.yml
Tests/.swiftlint.yml

[SwiftLint] Enable function_body_length rule

---

Quick.podspec

http://blog.cocoapods.org/CocoaPods-1.5.0/#modular-headers
Possibly fix #923.

[CocoaPods] Use modular headers

---

Quick.xcodeproj/project.pbxproj

Remove unnecessary TVOS_DEPLOYMENT_TARGET build setting in Quick-iOS target

---

Quick.xcodeproj/project.pbxproj
Sources/Quick/QuickTestObservation.swift
Sources/QuickObjectiveC/QuickSpec.m
Tests/QuickTests/QuickFocusedTests/FocusedTests.swift
Tests/QuickTests/QuickTests/Helpers/QuickSpecRunner.swift

Let's configure all example groups of QuickSpec subclasses at first using XCTestObservation's `testBundleWillStart(_:)`.
refs:
- #873 
- Fixes #886

Fix focus behavior

---

Sources/Quick/DSL/DSL.swift
Sources/Quick/DSL/World+DSL.swift
Sources/Quick/Example.swift
Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift

This adds support to catching thrown errors inside `it` blocks. Will fix #403.
Currently, you'd have to use one of Nimble's matchers such as 
```swift
it("works") {
expect { try foo }.toNot(throwError())
}
```
With this, you'd just have:
```swift
it("works") {
try foo
}
```
This also is similar to `XCTest`, which supports functions being marked as `throws` (and the test fails if they do throw). 
This is still WIP because I don't know how to proceed on some places (will add comments).

Initial support to implicit errors

---

Sources/Quick/QuickSpec.swift
Sources/QuickObjectiveC/QuickSpec.m

refs:
- #888 
- Possibly fix #939

Delegate `recordFailure` to `QuickSpec.current`

---

Sources/Quick/QuickSpec.swift
Sources/QuickObjectiveC/QuickSpec.m

Cherry-picks #990 into `2.x-branch`.

[2.x] Delegate `recordFailure` to `QuickSpec.current`

---

Dangerfile

There would be an error such as:
> 
> 
> ## Danger has errored
> [!] Invalid `Dangerfile` file: bad URI(is not URI?): "https://api.github.com/organizations/8083968/public_members/dependabot[bot]". Updating the Danger gem might fix the issue. Your Danger version: 8.0.0, latest Danger version: 8.0.4
> 
> ```
>  #  from Dangerfile:38
>  #  -------------------------------------------
>  #  # Make a note about contributors not in the organization
>  >  unless github.api.organization_member?('Quick', github.pr_author)
>  #    # Pay extra attention if they modify the podspec
>  #  -------------------------------------------
> ```
> 
> <p align="right" data-meta="generated_by_danger">
>   Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
> </p>
>

[Dangerfile] Avoid passing a bot account name to `github.api.organization_member`

---

Quick.podspec
Quick.xcodeproj/project.pbxproj

ref: Quick/Nimble#803
---
See https://xcodebuildsettings.com/#enable_testing_search_paths and https://developer.apple.com/documentation/xcode-release-notes/xcode-11_4-release-notes:
> Xcode introduced an “Enable Testing Search Paths” build setting to improve support for test support frameworks and libraries. This build setting is on by default for test bundle targets, as well as for targets which explicitly include XCTest.framework in their “Link Binary With Libraries” list. Source files in such targets can now import XCTest without setting any custom search paths. (51117167)

Set ENABLE_TESTING_SEARCH_PATHS to YES

---

.github/workflows/ci.yml
Documentation/en-us/TestingApps.md

iOS SDK 13.0 (Xcode 11) does not call `UIViewController.viewDidAppear()` anymore when calling  ` viewController.beginAppearanceTransition()` and `UIViewController.endAppearanceTransition()` when testing views directly.  This looks like a behavior change not directly related to Quick, but think the docs need to be updated.
See https://github.com/Quick/Quick/issues/941.

Update docs - vieiwDidAppear not be called automatically in iOS SDK 13.0

---

Sources/QuickObjectiveC/DSL/QCKDSL.h

Re-add missing QUICK_EXPORT to Objective-C DSL

---

Quick.podspec

Hi! 👋
I'm working on many libraries for React Native (https://github.com/expo/expo specifically) and I'd like to migrate our existing unit tests from XCTest to Quick and Nimble. Each library is shipped as a pod and its tests are provided as CocoaPods `test_spec`, as you can see here:
https://github.com/expo/expo/blob/1eb8a11176368994763629de3db74478de27fa9f/packages/expo-modules-core/ios/ExpoModulesCore.podspec#L34-L39
However, with Quick and Nimble as a `test_spec` dependency, when I run the tests from Xcode I'm getting such errors:
As I've already seen similar issues with other libraries, I **quick**ly checked if `Quick.podspec` and `Nimble.podspec` have the `header_dir` set. They don't, so I added it and used these custom podspecs in my `Podfile` as here: …

Specify header_dir in the podspec

---

Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift

Hello.
Thank you for Quick.
Refactored `FunctionalTests_ItSpec` with less `[String]()`.

Less [String]()

---

Package.swift

No
No
Warnings are being generated by Xcode when the Quick was used using SPM

Excluding Info.plist files from Swift Package

---

Sources/Quick/DSL/DSL.swift

Fixes a typo in the documentation for the `xitBehavesLike` function

docs(DSL): fix typo

---

Sources/QuickObjectiveC/XCTestSuite+QuickTestSuiteBuilder.m

Fix for #1094 
1. Create project with one failing Quick spec in Xcode 12.5+
2. Run all tests
3. Now we have 1/1 failed tests
4. Rerun that single test by clicking the corresponding test diamond in the gutter
Expected results:
- Test failed
Actual results:
- Test succeeded
Starting with Xcode 12.5 XCTest.framework not calling `testSuiteForTestCaseWithName:` when running individual tests.
Instead it calls `testClassSuitesForTestIdentifiers:skippingTestIdentifiers:randomNumberGenerator:`
So we swizzle `testClassSuitesForTestIdentifiers:skippingTestIdentifiers:randomNumberGenerator:` and  create resulting suite where tests from all QuickTestSuites are stored

Fix individual tests run in Xcode 12.5

---

Sources/Quick/QuickTestObservation.swift
Sources/QuickObjectiveC/QuickSpec.m

Fix for #1123 
Because Quick does not work with Xcode 13.3.
When running tests in Xcode 13.3 notification `testBundleWillStart` is called after method `testInvocations` of each QuickTest subclass. 
This means that when Xcode asks your QuickTest subclass for test cases to run (calling `testInvocations`) it gets empty array because test cases array will be computed on `testBundleWillStart` call.
As suggested @jessesquires this is step 1 with most important changes that fix the problem. Step 2 will contain a bit of refactoring with extracting examples loading into separate class as now it looks a bit strange that `QuickSpec.testInvocations` method calls `QuickSpecObservation`.

Critical! Fix test cases discoverage in Xcode 13.3

---

Sources/Quick/Configuration/QuickConfiguration.swift
Sources/Quick/QuickTestObservation.swift

Use Objective-C runtime's `isSubclass(of:)` API for checking superclass

---

Documentation/en-us/ConfiguringQuick.md

This change fixes the docs for the `configure` method - which takes a non-named argument.
- What behavior was changed? None
- What code was refactored / updated to support this change? None
- What issues are related to this PR? Or why was this change introduced? Because the docs were wrong.

Fix Swift docs for non-named `configure` argument.

---

Gemfile
Gemfile.lock
Sources/Quick/World.swift
Sources/QuickObjectiveC/QuickSpec.m
Tests/QuickTests/QuickAfterSuiteTests/AfterSuiteTests.swift

The logic used to determine whether the `afterSuite` blocks should be called or not.
It also adds missing gems required for the `bundle exec rake` command mentioned in the `CONTRIBUTING.md` file.
`World.swift`
- What issues are related to this PR? Or why was this change introduced? 
Fixes #809.
Related to #488.

Fix `afterSuite` blocks not running when having excluded tests

---

Quick.xcodeproj/project.pbxproj
Sources/Quick/QuickSelectedTestSuiteBuilder.swift
Sources/Quick/QuickTestSuite.swift
Sources/QuickObjectiveC/XCTestSuite+QuickTestSuiteBuilder.m
Tests/QuickTests/QuickTestHelpers/XCTestCaseProvider.swift
Tests/QuickTests/QuickTests/FunctionalTests/ObjC/SelectedTests+ObjC.m
Tests/QuickTests/QuickTests/FunctionalTests/QuickSpec_SelectedTests.swift

This implements half of the functionality of [zacwest's PR](https://github.com/Quick/Quick/pull/936), but in a more maintainable manner (this implementation uses `XCTTestIdentifier -components`, whereas zacwest's tries to parse the string from `_identifierString`, which doesn't work as well because `_identifierString` can return either swift-formatted (`foo/myMethod()`) or objc-formatted (`foo/myMethod`) identifiers).
This allows you to select an individual (or set of) test from the Test Navigator in Xcode and run only that test.
This also adds tests guaranteeing the functionality works, though it is split between tests written in objc and swift.
- This …

Add support for running a single test

---

Quick.xcodeproj/xcshareddata/xcschemes/Quick-iOS.xcscheme
Quick.xcodeproj/xcshareddata/xcschemes/Quick-macOS.xcscheme
Quick.xcodeproj/xcshareddata/xcschemes/Quick-tvOS.xcscheme
Sources/QuickObjectiveC/XCTestSuite+QuickTestSuiteBuilder.m
Tests/QuickTests/QuickTests/FunctionalTests/ObjC/SelectedTests+ObjC.m

Solves #1139
This reverts 90ec83d37cc8e943944ee07ed0ea9cf2f541c6b1. The original PR that introduced it has since been deleted, so I'm unsure exactly of the intention of that contribution. The commit mentions being able to run a selected test, which is still doable with this revert.
Tests here is setting some of the test targets for each of iOS, tvOS, and macOS to run in parallel.

Fix running tests in parallel

---

Sources/Quick/Example.swift
Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift

When running on macOS, skipped tests will be reported in the Xcode test navigator, like so:
The skipped line will *not* be marked in the source code editor. It appears that Xcode only does that for statically defined tests (those marked <img width="16" alt="static test" src="https://user-images.githubusercontent.com/5703449/131739328-cdb175e5-abcb-422d-bdf1-c80583c918b1.png">), not runtime tests (those marked <img width="16" alt="run-time test" src="https://user-images.githubusercontent.com/5703449/131739332-740396a7-e2b6-4f4e-acff-d49d079db389.png">), which is what Quick uses exclusively.
Future direction: when some tests are "focused", should we mark all …

Report skipped tests to Xcode

---

Quick.xcodeproj/project.pbxproj
Sources/Quick/Configuration/QuickConfiguration.swift
Sources/Quick/QuickTestObservation.swift
Sources/Quick/SubclassDetection.swift
Tests/QuickTests/QuickTests/FunctionalTests/SubclassDetectionSpec.swift
Tests/QuickTests/QuickTests/Helpers/QuickSpecRunner.swift

Also grabs the list of objc classes in a much more thread-safe way.
Fixes #1155
---
This changes how we determine if a given class is a subclass of QuickSpec or QuickConfiguration. This is likely slower than using `isSubclass(of:)`. However, according to the radar @tiarnann filed, this should eliminate the sporadic crashes in subclass detection that keep coming up. So that's definitely worth fixing the issue.
Additionally, this replaces usage of `objc_getClassList` with `objc_copyClassList`. Apparently the get method has potential race conditions that can cause crashes, while the copy method does not.

Fix sporadic crashes caused by finding classes that don't play well with isSubclass(of:)

---

.github/workflows/ci-swiftpm.yml
.github/workflows/ci-xcode.yml
Tests/QuickTests/QuickTests/FunctionalTests/QuickSpec_SelectedTests.swift

The Sequence assertion API was changed (simplified) in the Nimble v9 -> v10 update. This updates the test we had that used it and was broken by it.
This PR also updates the github workflows to ensure that tests run when we update the Nimble submodule in a PR. So that we don't do this again.

Fix tests broken by Nimble 10 update

---

Documentation/en-us/QuickExamplesAndGroups.md
Quick.xcodeproj/project.pbxproj
Sources/Quick/DSL/DSL.swift
Sources/Quick/DSL/World+DSL.swift
Sources/Quick/Example.swift
Sources/Quick/ExampleGroup.swift
Sources/Quick/Hooks/ExampleHooks.swift
Sources/QuickObjectiveC/DSL/QCKDSL.h
Sources/QuickObjectiveC/DSL/QCKDSL.m
Tests/QuickTests/QuickTests/FunctionalTests/JustBeforeEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/ObjC/JustBeforeEachTests+Objc.m

**Overview**
Quick is missing the ability to assign values to variables in interior blocks, but read those variables in a common exterior block. This is similar to the lazy evaluation of the `let` operation in rspec. This change introduces the ability to assign variable values prior to the execution of the `beforeEach` blocks.
**What behavior was changed?**
A new operator, `assignBefore`, was added to the DSL and logic of the `Example` class
**What code was refactored / updated to support this change?**
I have amended the core logic of the `Example` class, added `assignBefore` to the DSL, and added a new array of closures stored by the `ExampleHooks` class.
**What issues are related to this PR? Or why was this change introduced?**
I have written a blog post describing my rationale. See …

Introduce an `assignBefore` operator

---

Sources/Quick/DSL/DSL.swift
Sources/Quick/DSL/World+DSL.swift
Tests/QuickTests/QuickFocusedTests/FocusedTests.swift

Fixes https://github.com/Quick/Quick/issues/1181
If you have two functions that take a closure - one takes an async closure, and the other takes a sync closure - unless you specifically make an async call, swift will pick the sync version of the function. Because we had both sync and async versions of `fit` available, Swift would default to the sync version.
I noticed similar issues in `xit`, `pending` and `justBeforeEach`. This PR fixes those as well.

Support async in fit

---

Sources/QuickObjectiveC/DSL/QCKDSL.h
Tests/QuickTests/QuickTests/FunctionalTests/DescribeTests.swift

This should reduce confusion in the swift compiler reporting errors.

Make Objective-C API unavailable in Swift.

---

.github/workflows/ci-swiftpm.yml
.github/workflows/ci-xcode.yml
Package.resolved
Package.swift
Sources/Quick/Examples/Example.swift
Sources/Quick/QuickMain.swift
Sources/Quick/QuickTestObservation.swift
Tests/QuickTests/QuickTests/Fixtures/FunctionalTests_BehaviorTests_Behaviors.swift
Tests/QuickTests/QuickTests/Fixtures/FunctionalTests_SharedExamplesTests_SharedExamples.swift
Tests/QuickTests/QuickTests/FunctionalTests/AroundEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/BundleModuleNameTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/CurrentSpecTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/SubclassDetectionSpec.swift

[Nimble 11.2.0](https://github.com/Quick/Nimble/releases/tag/v11.2.0) fixed the issue where any usage of async behavior in a test would cause the compiler to think that any usage of `expect` was taking in an async closure. This PR pulls in the now-current [11.2.1 version of Nimble](https://github.com/Quick/Nimble/releases/tag/v11.2.1), and sets the Package.swift to require at least 11.2.0.
This should make life significantly easier for those contributing to Quick.

Update Nimble to 11.2.1, remove now-unnecessary usage of awaits in tests. Drop support for swift 5.6/Xcode 13.3.1

---

Quick.xcodeproj/project.pbxproj
Sources/Quick/TestState.swift
Tests/QuickTests/QuickTests/FunctionalTests/TestStateSpec.swift

Adds a `TestShared` property wrapper as suggested in
- #1178
It will always reset a property to nil at the end of a test. If the property wrapper is created with a value, the value will be set at the start of a test.

Added a `TestState` property wrapper.

---

Sources/Quick/DSL/DSL.swift
Sources/Quick/QuickSpec.swift
Sources/Quick/TestState.swift
Sources/Quick/World.swift
Sources/QuickObjectiveC/DSL/QCKDSL.h
Sources/QuickObjectiveC/QuickSpec.h
Sources/QuickObjectiveC/QuickSpec.m
Tests/QuickIssue853RegressionTests/SubclassOfSubclassWithStructPropertyTests.swift
Tests/QuickTests/QuickAfterSuiteTests/AfterSuiteTests.swift
Tests/QuickTests/QuickFocusedTests/FocusedTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/AfterEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/AroundEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/BeforeEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/BeforeSuiteTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/BehaviorTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/BundleModuleNameTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/Configuration/AfterEach/Configuration+AfterEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/Configuration/BeforeEach/Configuration+BeforeEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/ContextTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/CrossReferencingSpecs.swift
Tests/QuickTests/QuickTests/FunctionalTests/CurrentSpecTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/DescribeTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/JustBeforeEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/PendingTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/QuickSpec_SelectedTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/SharedExamples+BeforeEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/SharedExamplesTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/SubclassDetectionSpec.swift
Tests/QuickTests/QuickTests/FunctionalTests/TestStateSpec.swift

Cherry-Picked out of https://github.com/Quick/Quick/pull/1199. That PR still needs more work, but I think making QuickSpec.spec be a static method would be a good idea.
This is definitely related to seeing the [new changes to ResultBuilder](https://forums.swift.org/t/improved-result-builder-implementation-in-swift-5-8/63192) getting publicized and wanting to see if having AsyncSpec be based on ResultBuilder is actually worthwhile now.
> Objective-C users (particularly those who use the QuickSpecBegin/QuickSpecEnd macros) have the easiest migration path: they don't have to do anything. Others will need to apply a regex (swift: s/override func spec/override class func spec/; Obj-c: s/- spec/+ spec/). Assuming this approach survives a more thorough investigation, future work would be to …

Transition QuickSpec.spec to be a static method.

---

Quick.xcodeproj/project.pbxproj
Sources/Quick/Async/AsyncExampleGroup.swift
Sources/Quick/Async/AsyncSpec.swift
Sources/Quick/Async/AsyncWorld.swift
Sources/Quick/DSL/AsyncDSL.swift
Sources/Quick/DSL/AsyncWorld+DSL.swift
Sources/Quick/Examples/Example.swift
Sources/Quick/QuickSpec.swift
Sources/QuickObjectiveC/AsyncSpec+testMethodSelectors.m
Sources/QuickObjectiveC/QuickSpec.m
Tests/QuickTests/QuickTests/Fixtures/FunctionalTests_AsyncBehaviorTests_AsyncBehaviors.swift
Tests/QuickTests/QuickTests/FunctionalTests/Async/ItAsyncTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/ItTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/ObjC/ItTests+ObjC.m

Apply the spec demangling as seen in AsyncSpec to QuickSpec.
There's a mild chance that this will break any scripts relying on mangled test names. I'm ok with that so long as we call it out in the release notes.
Big thanks to @bnickel for the [initial spike](https://github.com/Quick/Quick/pull/1167) on all this work, as well as for the idea behind it.

Demangle QuickSpec test names as much as possible

---

Quick.xcodeproj/project.pbxproj
Sources/Quick/Async/AsyncSpec.swift
Sources/Quick/QuickSpec.swift
Sources/Quick/TestSelectorNameProvider.swift
Sources/QuickObjectiveC/QuickSpec.m
Tests/QuickTests/QuickTests/FunctionalTests/TestSelectorNameProviderTests.swift

Fixes https://github.com/Quick/Quick/issues/1208
Adds the ability to use legacy (encoded) test selector names when the `QUICK_USE_LEGACY_TEST_SELECTOR_NAMES` environment variable is set (to any value).
This does that by pulling out the logic for calculating test selectors into a separate component (which needs to be a class because objc compatibility), where both the logic for calculating test selector names and deciding which one to use exists. Then the appropriate spots in `AsyncSpec.swift`, `QuickSpec.swift` and `QuickSpec.m` were updated to use this new component.

Add mechanism to fallback to legacy test selector names

---

Sources/Quick/TestSelectorNameProvider.swift

Changes the environment variable we query to use encoded test selector names from  `QUICK_USE_LEGACY_TEST_SELECTOR_NAMES` to `QUICK_USE_ENCODED_TEST_SELECTOR_NAMES`.
CC @tikitu (who suggested a rename of the flag), @stonko1994 (who suggested we provide this option in the first place).

Don't imply that we plan to remove the option to force encoded test selector names

---

Documentation/en-us/DataDrivenExamples.md
Documentation/en-us/QuickExamplesAndGroups.md
Documentation/en-us/SharedExamples.md
Documentation/en-us/TestUsingTestDoubles.md
Documentation/en-us/TestingApps.md
Documentation/ja/QuickExamplesAndGroups.md
Documentation/ja/SharedExamples.md
Documentation/ja/TestUsingTestDoubles.md
Documentation/ja/TestingApps.md
Documentation/ko-kr/QuickExamplesAndGroups.md
Documentation/ko-kr/SharedExamples.md
Documentation/ko-kr/TestUsingTestDoubles.md
Documentation/ko-kr/TestingApps.md
Documentation/pt-br/SharedExamples.md
Documentation/zh-cn/QuickExamplesAndGroups.md
Documentation/zh-cn/SharedExamples.md
Documentation/zh-cn/TestUsingTestDoubles.md
Documentation/zh-cn/TestingApps.md
Quick Templates/Quick Spec Class.xctemplate/Swift/___FILEBASENAME___.swift
README.md

Hi, I'm @coffmark. Thanks for always maintaining !
- I converted `override func spec() { ... }` to `override class func spec() { ... }` in docs.
- Docs.
- None.

[doc] Corrected to class method

---

Documentation/en-us/AsyncAwait.md
Documentation/en-us/ConfiguringQuick.md
Documentation/en-us/InstallingQuick.md
Documentation/en-us/TestUsingTestDoubles.md

Re-adds documentation on `AsyncAwait`, updated for Quick 7.
Adds documentation on making mocks of async functions, using a methodology I came up with a few months ago.
Removes marking the Swift Package Manager distribution as experimental.

Update the english documentation for Quick 7

---

Sources/Quick/DSL/AsyncDSL.swift
Sources/Quick/DSL/AsyncWorld+DSL.swift
Tests/QuickTests/QuickTests/FunctionalTests/Async/PendingAsyncTests.swift

Fixes https://github.com/Quick/Quick/issues/1219
Thanks @stonko1994!

Allow xit in the Async DSL to take in async closures

---

Sources/Quick/Callsite.swift
Sources/Quick/Examples/AsyncExample.swift
Sources/Quick/Examples/Example.swift

Noticed a bug (type conflict) between Nimble's definition of `FileString` and Quick's definition of `FileString`.
For reference/posterity, here's Nimble's definition:
```swift
#if !canImport(Darwin)
public typealias FileString = StaticString
#else
public typealias FileString = String
#endif
```
And here's Quick's definition of `FileString`:
```swift
#if SWIFT_PACKAGE
public typealias FileString = StaticString
#else
public typealias FileString = String
#endif
```
(The reasoning for FileString to exist in the first place is because objective-c cannot generate StaticString)
Basically, Quick makes the assumption that SWIFT_PACKAGE = objective-c is unavailable, which is not a valid assumption. This PR fixes that, and goes beyond to fix some longstanding warnings when using Quick from SPM.
This …

Correct a few places where we falsely assume "SWIFT_PACKAGE" == not darwin

---

Sources/Quick/Async/AsyncWorld.swift
Sources/Quick/Examples/AsyncExample.swift
Sources/Quick/World.swift
Tests/QuickTests/QuickTests/FunctionalTests/Configuration/AfterEach/Configuration+AfterEachAsyncTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/Configuration/BeforeEach/Configuration+BeforeEachAsyncSpec.swift

This PR ensures documented behavior below.
https://github.com/Quick/Quick/blob/v7.0.2/Documentation/en-us/ConfiguringQuick.md#adding-global-beforeeach-and-aftereach-closures

Ensure beforeEach in Configuration run for AsyncSpec

---

Documentation/en-us/QuickExamplesAndGroups.md
Sources/Quick/Configuration/QCKConfiguration.swift
Sources/Quick/DSL/World+DSL.swift
Sources/Quick/Examples/AsyncExample.swift
Sources/Quick/Examples/Example.swift
Sources/Quick/Hooks/AsyncExampleHooks.swift
Sources/Quick/Hooks/Closures.swift
Sources/Quick/Hooks/ExampleHooks.swift
Sources/Quick/Hooks/SuiteHooks.swift
Sources/QuickObjectiveC/DSL/QCKDSL.h
Sources/QuickObjectiveC/DSL/QCKDSL.m
Tests/QuickTests/QuickTests/FunctionalTests/AfterEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/Async/AfterEachAsyncTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/Async/BeforeEachAsyncTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/BeforeEachTests.swift

Fixes #1122.
In a non-breaking manner, adds support for throwing expressions in `beforeEach`, `justBeforeEach`, and `afterEach`. These behave similarly to if you used the `setupWithError` and `teardownWithError` methods on XCTestCase: The subsequent `beforeEach`s are skipped. The test is skipped/not run. The appropriate `afterEach`s still run (but not nested `afterEach`s).
This does not affect Objective-C tests at all. i.e. None of the setup or teardown functions support an `NSError **` parameter for throwing. Similarly, you cannot throw an NSException to get this same behavior.
The logic for this is implemented in `Example`/`AsyncExample`: When a setup/teardown throws, then we set a `cancelTests` variable that is checked before running another closure for the test. With the way this …

Allow beforeEach, justBeforeEach, and afterEach in Swift to throw

---

README.md

Fixes #774
Documentation update to the README.
Gives more correct instructions for installing Quick and Nimble via Cocoapods.
Also provides instructions for installing Quick and Nimble via Swift Package Manager in the readme.

Improve documentation for installing Quick and Nimble via Cocoapods in the README.

---

Sources/Quick/DSL/DSL.swift
Tests/QuickTests/QuickTests/FunctionalTests/PendingTests.swift

Fixes #1227 for SyncDSLUser. I have no plans to make `itBehavesLike(_ name: String)`, `fitBehavesLike(_ name: String)`, nor `xitBehavesLike(_ name: String)` a thing for Async tests.
This adds a public `xitBehavesLike` for quickly pending out the string-based `itBehavesLike` api in `QuickSpec` and `Behavior`. Something which I apparently forgot to do when I created `SyncDSLUser`.

Make a public xitBehavesLike(_ name: String) for SyncDSLUser

---

Documentation/en-us/TestOrdering.md
Quick.xcodeproj/project.pbxproj
Sources/Quick/Async/AsyncExampleGroup.swift
Sources/Quick/ExampleGroup.swift
Tests/QuickTests/QuickTests/FunctionalTests/Async/AsyncOrderingTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/OrderingTests.swift

Fixes #759
See also #766, which this is inspired by.
This suggests to XCTest that we run tests in the order they are defined in. As #766 notes, this is a suggestion and XCTest can and will easily ignore that in certain circumstances. This is even desirable, as the preferred mechanism for randomizing test execution order is through enabling "Randomize Execution Order" in your xctestplan.
This is a departure from how tests were previously ordered. Before we didn't suggest an order, but in practice, tests would usually run as un-nested examples first, then nested examples later (unless you did any kind of filtering - including using test gems -, then tests would run in lexicographical order). Now we suggest that tests run in the order they are defined in. I don't consider this to be a …

Attempt to run tests within a QuickSpec or AsyncSpec in the order they are defined in

---

Quick.xcodeproj/project.pbxproj
Sources/Quick/TestState.swift
Tests/QuickTests/QuickTests/FunctionalTests/TestStateSpec.swift

Adds a `TestState` property wrapper
- As suggested in #1178
- Then added in #1186
- Then removed in #1199
The main difference from the original implementation is it tries to detect which "World" is currently running tests, then add's the `afterEach`/`aroundEach` to that world. I'm not 100% sure if that's the right approach or if there's another way to add those to the current world.
From the original PR description
> It will always reset a property to nil at the end of a test. If the property wrapper is created with a value, the value will be set at the start of a test.

Added a TestState property wrapper, again :D

---

Sources/Quick/TestState.swift
Tests/QuickTests/QuickTests/FunctionalTests/TestStateSpec.swift

Currently, a property with `@TestState` will have its value reset to `nil` before any `afterEach` in the same `ExampleGroup` is run. This is because:
- the `@TestState` needs to be defined first so the tests can use it
- the `@TestState` was adding an `afterEach` to the current `ExampleGroup`
- the `afterEach` closures are run in the order they are defined in an `ExampleGroup`
This causes the `afterEach` resetting the `TestState` value to always be run before the `afterEach` closures defined in the same `ExampleGroup`.
This is an issue when a test needs to do additional cleanup using the value from `TestState. Ideally the value in the `TestState` would only be cleaned up after all the code in the test has finished running.
```swift
@TestState var tempDir: URL!
beforeEach {
tempDir = …
```

Updated TestState to remove the value after the test.

---

script/release

Fixes #949.
We haven't used the old `release` script in over a year. This updates the `release` script to follow the process I've been manually engaging in. Notably, this now autogenerates the docs & a Carthage framework binary. Additionally, it no longer requires us to write up release notes prior to releasing (the release notes referenced by the signed git tag now just point to GitHub). Instead, it uses the `gh` GitHub CLI to autogenerate release notes (and opens the release notes page after the fact to let us edit them after the fact).
This still requires us to GPG sign our release tags. Which we really should be doing, but haven't been.

Update release script to generate a carthage binary and include it in the release.

---

.github/workflows/carthage.yml
.github/workflows/release.yml
Rakefile
script/release

Build the Quick Carthage artifact on Xcode 14, which corresponds to swift 5.7 - the oldest version we currently support.
Remove building the Carthage artifact from the release script, because GitHub actions should be doing this for us.
Add a GitHub PR action to verify that Carthage artifacts can actually be built.

Build carthage artifacts as a github action.

---

Sources/Quick/Async/AsyncSpec.swift

Fixes #1258 
Sometimes, Using TestState in AsyncSpec would crash. I traced this down to a race condition where a new test could be started/running, and then we would unset `AsyncSpec.current`.
The diff here is fairly small, so let's step through it:
This is the actual test method that we create for XCTest, example.run is when we actually run the test code.
Was:
```swift
spec.example = example
Task {
await example.run()
completionHandler()
AsyncSpec.current = nil
}
```
Now:
```swift
Task {
spec.example = example
await example.run()
AsyncSpec.current = nil
completionHandler()
}
```
While I'm fairly certain that moving `spec.example = example` into the Task isn't necessary, I also know that it doesn't hurt. For reference, as a side effect of setting `spec.example`, we also set …

Fix crash in AsyncSpec when using TestState

---

Sources/Quick/Examples/AsyncExample.swift
Sources/Quick/Examples/Example.swift
Tests/QuickTests/QuickTests/FunctionalTests/AfterEachTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/Async/AfterEachAsyncTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/Async/BeforeEachAsyncTests.swift
Tests/QuickTests/QuickTests/FunctionalTests/BeforeEachTests.swift

Bugfix. When you throw an XCTSkip or StopTest error in `beforeEach`, `afterEach`, or `aroundEach`, then we should respect that and properly handle them (instead of as standard errors).

Respect XCTSkip and StopTest errors in beforeEach, afterEach and aroundEach

---

Sources/Quick/DSL/AsyncDSL.swift
Sources/Quick/DSL/DSL.swift

Add a remark to the synchronous version to prompt users to upgrade to Behavior.
Resolves #1278
Note: as of this PR, I have no plans to remove `sharedExamples` from the synchronous DSL.

Mark the async versions of sharedExamples as unavailable.

---

Documentation/en-us/SharedExamples.md

Hi there, in the SharedExamples docs, the use of the Behavior class is slightly incorrect in that it names the context param `context` instead of `aContext` like the class itself. This has the nasty consequence of shadowing any use of `context` blocks within the `spec` func.

named the context param aContext to match the actual protocol

---

Package.resolved
Package.swift
Package@swift-5.9.swift
Plugins/DefocusCommandPlugin/DefocusCommandPlugin.swift
Plugins/LintBuildToolPlugin/LintBuildToolPlugin.swift
Plugins/LintCommandPlugin/LintCommandPlugin.swift
Plugins/LintError/LintError.swift
Plugins/LintWarning/LintWarning.swift
Quick.podspec
Sources/QuickLint/DefocusFormatter.swift
Sources/QuickLint/DirectoryManager.swift
Sources/QuickLint/FileDetector.swift
Sources/QuickLint/FileInterface.swift
Sources/QuickLint/FocusLint.swift
Sources/QuickLint/QuickLint.swift
Sources/QuickLint/ServiceLocator.swift
Sources/QuickLint/Writer.swift
Tests/LintFixtures/Nesting/Nesting.swift
Tests/LintFixtures/SampleSpec.swift
Tests/QuickLintTests/DefocusCommandSpec.swift
Tests/QuickLintTests/DefocusFormatterSpec.swift
Tests/QuickLintTests/Fakes/FakeFileDetector.swift
Tests/QuickLintTests/Fakes/FakeFileInterface.swift
Tests/QuickLintTests/Fakes/FakeWriter.swift
Tests/QuickLintTests/FileDetectorSpec.swift
Tests/QuickLintTests/FocusLintSpec.swift
Tests/QuickLintTests/LintCommandSpec.swift
Tests/QuickLintTests/Result+CapturingAsync.swift

Oftentimes, teams who use Quick's spec focusing either have to be really diligent about removing focus, or write a script to check for focus (and either block the push, or fail CI). Usually the latter is chosen. In an effort to alleviate writing those scripts, I wrote QuickLint. Which detects focused specs in the current directory, and also allows you to defocus the specs.
QuickLint also serves as an example of how to write testable code, and how to use Quick, [Nimble](https://github.com/Quick/Nimble), and the new [Swift Fakes](https://github.com/Quick/swift-fakes) packages.
Upcoming in this PR are also build tool and command plugins (for SwiftPM and Xcode) to lint and defocus your specs.
New feature, doesn't break the public API. So... minor version bump!

Add QuickLint, a CLI tool to detect focused specs, and optionally remove the focus.

---

Sources/Quick/DSL/DSL.swift
Sources/Quick/DSL/World+DSL.swift
Sources/Quick/Examples/Example.swift
Sources/Quick/Hooks/Closures.swift
Sources/Quick/Hooks/SuiteHooks.swift
Sources/Quick/QuickSpec.swift

This is following the discussion I started here.
- https://github.com/Quick/Quick/discussions/1288
`XCTestCase` always calls synchronous tests on the main thread. This is to support testing UIKit types which can't be used on background threads. 
However when testing custom types annotated with `@MainActor` the compiler produces errors on uses in the tests like the following.
```
Main actor-isolated property 'stateSubject' can not be referenced from a non-isolated context
```
```
Call to main actor-isolated initializer 'init()' in a synchronous nonisolated context
```
For some unknown reason, the concurrency checking doesn't give the same errors for `@MainActor` UIKit types.
This PR adds `@MainActor` annotations to the `QuickSpec` before/after/it closures so the compiler knows that they …

Updated closures in QuickSpec to be annotated with MainActor

---

Package.resolved

Bumped SPM dependencies that cause issues when building targets with a `carthage`, which takes dependencies straight from `.resolved` file, using ones that have to build issues with Xcode 16.2.

Bump Cwl dependencies to fix Xcode 16 issues
